export type Track = "china" | "world";
export type Category = "政治" | "思想" | "科技" | "交流" | "战争" | "社会";
export type TemporalType = "point" | "range" | "series";

export type MaterialLearningNote = {
  /** 材料卡片承担的认知任务，例如“背景与条件”“行动与变化”“结果与影响”。 */
  focus?: string;
  /** 这份材料放回事件脉络后，需要补充给学习者的背景信息。 */
  context?: string;
  /** 口述时可以直接引用或转述的关键信息。 */
  clue?: string;
};

export type HistoryEvent = {
  id: string;
  title: string;
  year: number;
  endYear?: number;
  /**
   * point：单一时间点；range：持续发生；series：在一段时间内多次发生。
   * 未填写时，有 endYear 的事件按 range 处理，其余按 point 处理。
   */
  temporalType?: TemporalType;
  /** series 可选：用于结果中标出各次行动的年份。 */
  milestoneYears?: number[];
  track: Track;
  category: Category;
  place: string;
  summary: string;
  scene: string;
  roles: string[];
  question: string;
  keyPoints: string[];
  evidence: string[];
  /** 可选：逐份覆盖材料卡片的学习说明；未填写时由事件脉络自动生成。 */
  materialNotes?: MaterialLearningNote[];
  impact: string;
  relatedIds: string[];
  /** 可选：归位玩法使用的代表年份；未填写时使用 year。 */
  placementYear?: number;
  /** 可选：时间段/系列事件归位玩法使用的结束年份；未填写时使用 endYear。 */
  placementEndYear?: number;
  /** 可选：设为 false 时不生成归位题卡。 */
  placementEnabled?: boolean;
};

export type Period = {
  id: string;
  label: string;
  shortLabel: string;
  start: number;
  end: number;
  prompt: string;
};

export type Journey = {
  id: string;
  title: string;
  subtitle: string;
  question: string;
  description: string;
  color: string;
  eventIds: string[];
};

export const periods: Period[] = [
  { id: "origins", label: "文明起源", shortLabel: "起源", start: -3500, end: -200, prompt: "人类如何从村落走向城市与国家？" },
  { id: "empires", label: "古典帝国", shortLabel: "帝国", start: -206, end: 600, prompt: "辽阔帝国如何连接不同的人群？" },
  { id: "medieval", label: "中古世界", shortLabel: "中古", start: 581, end: 1368, prompt: "当长安、巴格达与欧洲城堡同时存在。" },
  { id: "encounters", label: "全球相遇", shortLabel: "相遇", start: 1368, end: 1750, prompt: "不同文明为何在海洋上选择了不同方向？" },
  { id: "industry", label: "工业与变革", shortLabel: "工业", start: 1750, end: 1914, prompt: "机器、革命与帝国如何重塑世界？" },
  { id: "wars", label: "战争与重建", shortLabel: "战争", start: 1914, end: 1949, prompt: "旧秩序崩塌之后，人们如何寻找新道路？" },
  { id: "today", label: "走向当代", shortLabel: "当代", start: 1945, end: 2020, prompt: "相互连接的世界如何形成？" },
];

export const events: HistoryEvent[] = [
  {
    id: "chrono-2a8aa784",
    title: "旧石器时代",
    year: -3000000,
    endYear: -10000,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "元谋人、北京人、山顶洞人",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-85ac651a",
    title: "新石器时代",
    year: -10000,
    track: "china",
    category: "思想",
    place: "中国",
    summary: "仰韶文化、龙山文化、河姆渡文化",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-ac14fe8d",
    title: "原始农业出现",
    year: -10000,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "原始农业出现",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-e00331df",
    title: "两河流域出现城市国家（苏美尔文明）",
    year: -3500,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "两河流域出现城市国家（苏美尔文明）",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-bf9640ac",
    title: "埃及统一，早王朝时期开始",
    year: -3100,
    track: "world",
    category: "政治",
    place: "世界",
    summary: "埃及统一，早王朝时期开始",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-61314a1c",
    title: "禹建立夏朝（中国第一个奴隶制王朝）",
    year: -2070,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "禹建立夏朝（中国第一个奴隶制王朝）",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-4c7db84f",
    title: "古巴比伦王国汉谟拉比即位",
    year: -1792,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "古巴比伦王国汉谟拉比即位",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-1c19de6d",
    title: "商汤灭夏，建立商朝",
    year: -1600,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "商汤灭夏，建立商朝",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-b06a67b1",
    title: "甲骨文、青铜文明",
    year: -1600,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "甲骨文、青铜文明",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-d2641cd8",
    title: "雅利安人入侵印度",
    year: -1500,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "雅利安人入侵印度",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-1fd6d49a",
    title: "种姓制度形成",
    year: -1500,
    track: "world",
    category: "政治",
    place: "世界",
    summary: "种姓制度形成",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-2fd07ba2",
    title: "武王伐纣，西周建立",
    year: -1046,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "武王伐纣，西周建立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-7d260516",
    title: "分封制、宗法制、礼乐制",
    year: -1046,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "分封制、宗法制、礼乐制",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-5cb20adc",
    title: "第一届古代奥林匹克运动会",
    year: -776,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "第一届古代奥林匹克运动会",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-b11a8253",
    title: "平王东迁洛邑，东周开始（春秋时期）",
    year: -770,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "平王东迁洛邑，东周开始（春秋时期）",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-410b5d44",
    title: "克利斯提尼改革",
    year: -508,
    track: "world",
    category: "思想",
    place: "世界",
    summary: "克利斯提尼改革",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-c69a78b5",
    title: "战国时期开始",
    year: -475,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "战国时期开始",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-8a359f7b",
    title: "铁器牛耕推广",
    year: -475,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "铁器牛耕推广",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-ce54e866",
    title: "希波战争结束",
    year: -449,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "希波战争结束",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-3db7618b",
    title: "《卡里阿斯和约》",
    year: -449,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "《卡里阿斯和约》",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-38b6bbd8",
    title: "伯罗奔尼撒战争",
    year: -431,
    endYear: -404,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "伯罗奔尼撒战争",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-0560c84c",
    title: "商鞅变法",
    year: -356,
    track: "china",
    category: "思想",
    place: "中国",
    summary: "商鞅变法",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-14e0cae5",
    title: "万年 人类在非洲出现",
    year: -300,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "万年 人类在非洲出现",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-28e6019c",
    title: "统一文字、货币、度量衡",
    year: -221,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "统一文字、货币、度量衡",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-cd7b8082",
    title: "刘邦建立西汉",
    year: -206,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "刘邦建立西汉",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-a12a7aa5",
    title: "休养生息",
    year: -206,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "休养生息",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-af2f79a2",
    title: "古巴比伦王国汉谟拉比颁布法典",
    year: -18,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "古巴比伦王国汉谟拉比颁布法典",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-78fd8856",
    title: "希腊城邦兴起",
    year: -8,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "希腊城邦兴起",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-b7fc4d42",
    title: "荷马时代结束",
    year: -8,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "荷马时代结束",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-ec0f23eb",
    title: "伯里克利时代",
    year: -5,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "伯里克利时代",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-a708588f",
    title: "罗马征服意大利半岛",
    year: -3,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "罗马征服意大利半岛",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-e603a19b",
    title: "罗马征服地中海地区",
    year: -2,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "罗马征服地中海地区",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-790c3148",
    title: "布匿战争",
    year: -2,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "布匿战争",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-09c1b066",
    title: "万年 农业革命开始（西亚两河流域）",
    year: -1,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "万年 农业革命开始（西亚两河流域）",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-b3bee333",
    title: "基督教在巴勒斯坦产生",
    year: -1,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "基督教在巴勒斯坦产生",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-0809182c",
    title: "阿拉伯帝国崛起",
    year: 8,
    track: "world",
    category: "政治",
    place: "世界",
    summary: "阿拉伯帝国崛起",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-d5a2cedb",
    title: "阿拉伯帝国地跨亚非欧三大洲",
    year: 8,
    track: "world",
    category: "政治",
    place: "世界",
    summary: "阿拉伯帝国地跨亚非欧三大洲",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-1266f378",
    title: "东汉建立",
    year: 25,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "东汉建立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-1e2a15a2",
    title: "光武中兴",
    year: 25,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "光武中兴",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-dfc19d6e",
    title: "曹丕建魏，东汉灭亡",
    year: 220,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "曹丕建魏，东汉灭亡",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-7b836a46",
    title: "西晋短暂统一",
    year: 280,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "西晋短暂统一",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-32b9874e",
    title: "米兰敕令",
    year: 313,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "米兰敕令",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-034115bd",
    title: "基督教合法化",
    year: 313,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "基督教合法化",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-63bf9bea",
    title: "东晋建立",
    year: 317,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "东晋建立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-940e2072",
    title: "北方十六国",
    year: 317,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "北方十六国",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-627bacdf",
    title: "北魏统一北方",
    year: 439,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "北魏统一北方",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-9371f72f",
    title: "欧洲进入中世纪",
    year: 476,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "欧洲进入中世纪",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-2bee9180",
    title: "查士丁尼法典编纂",
    year: 529,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "查士丁尼法典编纂",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-22a724d8",
    title: "隋朝建立",
    year: 581,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "隋朝建立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-ef8c0844",
    title: "589年统一全国",
    year: 581,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "589年统一全国",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-61e4c314",
    title: "唐朝建立",
    year: 618,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "唐朝建立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-11bc1002",
    title: "贞观之治、开元盛世",
    year: 618,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "贞观之治、开元盛世",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-41676a06",
    title: "穆罕默德出走麦地那，伊斯兰教创立",
    year: 622,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "穆罕默德出走麦地那，伊斯兰教创立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-abffcdc8",
    title: "穆罕默德出走麦地那（伊斯兰教历元年）",
    year: 622,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "穆罕默德出走麦地那（伊斯兰教历元年）",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-1a2f1f49",
    title: "贞观之治",
    year: 627,
    endYear: 649,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "贞观之治",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-ee50909b",
    title: "日本大化改新",
    year: 646,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "日本大化改新",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-5443f648",
    title: "安史之乱",
    year: 755,
    endYear: 763,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "安史之乱",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-0afd1e31",
    title: "唐朝由盛转衰",
    year: 755,
    endYear: 763,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "唐朝由盛转衰",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-7201b454",
    title: "查理曼帝国建立",
    year: 800,
    track: "world",
    category: "政治",
    place: "世界",
    summary: "查理曼帝国建立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-ff899167",
    title: "查理曼加冕称帝",
    year: 800,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "查理曼加冕称帝",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-77f088b9",
    title: "查理曼帝国",
    year: 800,
    track: "world",
    category: "政治",
    place: "世界",
    summary: "查理曼帝国",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-7efb2362",
    title: "中央集权加强",
    year: 960,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "中央集权加强",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-dececcc3",
    title: "基督教东西教会大分裂",
    year: 1054,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "基督教东西教会大分裂",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-2a3d2d8c",
    title: "基督教东西教会大分裂（天主教与东正教）",
    year: 1054,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "基督教东西教会大分裂（天主教与东正教）",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-368017ee",
    title: "王安石变法",
    year: 1069,
    track: "china",
    category: "思想",
    place: "中国",
    summary: "王安石变法",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-0d7707bb",
    title: "1125年灭辽，1127年灭北宋（靖康之变）",
    year: 1115,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "1125年灭辽，1127年灭北宋（靖康之变）",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-2bdb962b",
    title: "英国《大宪章》",
    year: 1215,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "英国《大宪章》",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-322ca118",
    title: "英国颁布《大宪章》",
    year: 1215,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "英国颁布《大宪章》",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-39215793",
    title: "马可·波罗来华",
    year: 1271,
    track: "world",
    category: "交流",
    place: "世界",
    summary: "马可·波罗来华",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-772ccd16",
    title: "元朝建立",
    year: 1271,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "元朝建立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-2cd935f6",
    title: "1279年统一全国",
    year: 1271,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "1279年统一全国",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-03aaa3c0",
    title: "马可·波罗返回威尼斯",
    year: 1295,
    track: "world",
    category: "交流",
    place: "世界",
    summary: "马可·波罗返回威尼斯",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-343076ad",
    title: "废丞相、设内阁",
    year: 1368,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "废丞相、设内阁",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-f5b72f96",
    title: "明成祖迁都北京",
    year: 1421,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "明成祖迁都北京",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-f948d265",
    title: "奥斯曼帝国攻陷君士坦丁堡",
    year: 1453,
    track: "world",
    category: "政治",
    place: "世界",
    summary: "奥斯曼帝国攻陷君士坦丁堡",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-6bef179b",
    title: "迪亚士到达好望角",
    year: 1487,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "迪亚士到达好望角",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-52859407",
    title: "达·伽马到达印度",
    year: 1497,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "达·伽马到达印度",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-dfb987e8",
    title: "葡萄牙人占据澳门（租居）",
    year: 1510,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "葡萄牙人占据澳门（租居）",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-62f3a667",
    title: "马丁·路德发表《九十五条论纲》",
    year: 1517,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "马丁·路德发表《九十五条论纲》",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-ad5566b6",
    title: "麦哲伦船队环球航行",
    year: 1519,
    endYear: 1522,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "麦哲伦船队环球航行",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-fdaeb9d4",
    title: "麦哲伦船队完成环球航行",
    year: 1519,
    endYear: 1522,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "麦哲伦船队完成环球航行",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-4a9d7031",
    title: "葡萄牙人取得澳门居住权",
    year: 1553,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "葡萄牙人取得澳门居住权",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-61d6d7f6",
    title: "隆庆开关，月港成为合法对外贸易港",
    year: 1567,
    track: "china",
    category: "交流",
    place: "中国",
    summary: "隆庆开关，月港成为合法对外贸易港",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-d03c5ba4",
    title: "英国击败西班牙\"无敌舰队\"",
    year: 1588,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "英国击败西班牙\"无敌舰队\"",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-9b08f952",
    title: "后金建立",
    year: 1616,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "后金建立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-b20b46b8",
    title: "1636年改国号为清",
    year: 1616,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "1636年改国号为清",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-a4ca0f48",
    title: "英国资产阶级革命开始",
    year: 1640,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "英国资产阶级革命开始",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-cf130c3f",
    title: "清军入关，明朝灭亡",
    year: 1644,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "清军入关，明朝灭亡",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-28f98060",
    title: "郑成功收复台湾",
    year: 1662,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "郑成功收复台湾",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-dd3017a0",
    title: "清朝设置台湾府，隶属福建省",
    year: 1684,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "清朝设置台湾府，隶属福建省",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-6178e267",
    title: "牛顿发表《自然哲学的数学原理》",
    year: 1687,
    track: "world",
    category: "思想",
    place: "世界",
    summary: "牛顿发表《自然哲学的数学原理》",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-6cdd7790",
    title: "英国\"光荣革命\"",
    year: 1688,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "英国\"光荣革命\"",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-c94d3bf1",
    title: "中俄签订《尼布楚条约》",
    year: 1689,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "中俄签订《尼布楚条约》",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-6fb40409",
    title: "英国颁布《权利法案》",
    year: 1689,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "英国颁布《权利法案》",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-7fe8e1ba",
    title: "君主立宪制确立",
    year: 1689,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "君主立宪制确立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-1a4aaea2",
    title: "清朝设置驻藏大臣",
    year: 1727,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "清朝设置驻藏大臣",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-efc78418",
    title: "清朝仅留广州一口通商",
    year: 1757,
    track: "china",
    category: "交流",
    place: "中国",
    summary: "清朝仅留广州一口通商",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-035ee994",
    title: "美国独立战争",
    year: 1775,
    endYear: 1783,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "美国独立战争",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-390661db",
    title: "《独立宣言》（1776年）",
    year: 1775,
    endYear: 1783,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "《独立宣言》（1776年）",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-79847136",
    title: "《人权宣言》",
    year: 1789,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "《人权宣言》",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-03d5abf3",
    title: "拿破仑称帝",
    year: 1804,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "拿破仑称帝",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-f9eca749",
    title: "法兰西第一帝国",
    year: 1804,
    track: "world",
    category: "政治",
    place: "世界",
    summary: "法兰西第一帝国",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-730ff0bb",
    title: "滑铁卢战役",
    year: 1815,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "滑铁卢战役",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-3540e6c6",
    title: "拿破仑帝国覆灭",
    year: 1815,
    track: "world",
    category: "政治",
    place: "世界",
    summary: "拿破仑帝国覆灭",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-3cc21eb0",
    title: "维也纳体系",
    year: 1815,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "维也纳体系",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-d54daf42",
    title: "《南京条约》签订，中国开始沦为半殖民地半封建社会",
    year: 1840,
    endYear: 1842,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "《南京条约》签订，中国开始沦为半殖民地半封建社会",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-7146750b",
    title: "欧洲革命浪潮",
    year: 1848,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "欧洲革命浪潮",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-7bef6f14",
    title: "太平天国运动",
    year: 1851,
    endYear: 1864,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "太平天国运动",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-403b3846",
    title: "克里米亚战争",
    year: 1853,
    endYear: 1856,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "克里米亚战争",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-fcb528bd",
    title: "《天津条约》《北京条约》",
    year: 1856,
    endYear: 1860,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "《天津条约》《北京条约》",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-fe137b7e",
    title: "达尔文发表《物种起源》",
    year: 1859,
    track: "world",
    category: "科技",
    place: "世界",
    summary: "达尔文发表《物种起源》",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-d7c7db95",
    title: "美国内战爆发",
    year: 1861,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "美国内战爆发",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-189ed026",
    title: "俄国农奴制改革",
    year: 1861,
    track: "world",
    category: "思想",
    place: "世界",
    summary: "俄国农奴制改革",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-6f9fcf23",
    title: "民族资本主义产生（继昌隆缫丝厂等）",
    year: 1870,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "民族资本主义产生（继昌隆缫丝厂等）",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-08124b7e",
    title: "普法战争",
    year: 1870,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "普法战争",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-85389f2f",
    title: "法兰西第二帝国覆灭",
    year: 1870,
    track: "world",
    category: "政治",
    place: "世界",
    summary: "法兰西第二帝国覆灭",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-f8d53013",
    title: "巴黎公社",
    year: 1871,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "巴黎公社",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-28c11aee",
    title: "德意志帝国建立",
    year: 1871,
    track: "world",
    category: "政治",
    place: "世界",
    summary: "德意志帝国建立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-2883b1b3",
    title: "德、奥、意三国同盟形成",
    year: 1882,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "德、奥、意三国同盟形成",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-9d011a96",
    title: "德、奥、意三国同盟",
    year: 1882,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "德、奥、意三国同盟",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-2d48173f",
    title: "中法战争",
    year: 1883,
    endYear: 1885,
    track: "china",
    category: "战争",
    place: "中国",
    summary: "中法战争",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-94c3df39",
    title: "\"法国不胜而胜，中国不败而败\"",
    year: 1883,
    endYear: 1885,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "\"法国不胜而胜，中国不败而败\"",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-ebf6135d",
    title: "甲午中日战争",
    year: 1894,
    endYear: 1895,
    track: "china",
    category: "战争",
    place: "中国",
    summary: "甲午中日战争",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-47c3d93a",
    title: "《马关条约》",
    year: 1894,
    endYear: 1895,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "《马关条约》",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-b6eee02b",
    title: "台湾被割占",
    year: 1894,
    endYear: 1895,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "台湾被割占",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-367e3524",
    title: "美国工业产值跃居世界第一",
    year: 1894,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "美国工业产值跃居世界第一",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-40944d54",
    title: "公车上书",
    year: 1895,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "公车上书",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-17174c2c",
    title: "维新思想传播",
    year: 1895,
    track: "china",
    category: "思想",
    place: "中国",
    summary: "维新思想传播",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-90c6f846",
    title: "列宁主义诞生",
    year: 1895,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "列宁主义诞生",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-d1701dd7",
    title: "戊戌变法（百日维新）",
    year: 1898,
    track: "china",
    category: "思想",
    place: "中国",
    summary: "戊戌变法（百日维新）",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-785658e7",
    title: "美西战争",
    year: 1898,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "美西战争",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-1b03529f",
    title: "义和团运动",
    year: 1899,
    endYear: 1900,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "义和团运动",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-2186fef1",
    title: "美国提出\"门户开放\"政策",
    year: 1899,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "美国提出\"门户开放\"政策",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-bae9ca74",
    title: "八国联军侵华",
    year: 1900,
    track: "china",
    category: "战争",
    place: "中国",
    summary: "八国联军侵华",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-9795030b",
    title: "德国物理学家普朗克提出量子论",
    year: 1900,
    track: "world",
    category: "科技",
    place: "世界",
    summary: "德国物理学家普朗克提出量子论",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-65a4b945",
    title: "《辛丑条约》签订",
    year: 1901,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "《辛丑条约》签订",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-151c3457",
    title: "中国完全沦为半殖民地半封建社会",
    year: 1901,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "中国完全沦为半殖民地半封建社会",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-2df8b3c3",
    title: "莱特兄弟发明飞机",
    year: 1903,
    track: "world",
    category: "科技",
    place: "世界",
    summary: "莱特兄弟发明飞机",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-39f98e00",
    title: "中国同盟会成立",
    year: 1905,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "中国同盟会成立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-9da999b2",
    title: "三民主义提出",
    year: 1905,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "三民主义提出",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-3bb6fca6",
    title: "废除科举制",
    year: 1905,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "废除科举制",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-fb870372",
    title: "爱因斯坦提出相对论",
    year: 1905,
    track: "world",
    category: "科技",
    place: "世界",
    summary: "爱因斯坦提出相对论",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-771833a9",
    title: "英、法、俄三国协约",
    year: 1907,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "英、法、俄三国协约",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-53a77647",
    title: "两大军事集团形成",
    year: 1907,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "两大军事集团形成",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-723eab0b",
    title: "推翻清朝统治",
    year: 1911,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "推翻清朝统治",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-c5a3498e",
    title: "清帝退位",
    year: 1912,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "清帝退位",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-d3eee214",
    title: "《临时约法》",
    year: 1912,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "《临时约法》",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-28c49fec",
    title: "新文化运动开始（民主与科学）",
    year: 1915,
    track: "china",
    category: "思想",
    place: "中国",
    summary: "新文化运动开始（民主与科学）",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-002135b5",
    title: "俄国二月革命",
    year: 1917,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "俄国二月革命",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-3b831007",
    title: "苏俄建立",
    year: 1917,
    track: "world",
    category: "政治",
    place: "世界",
    summary: "苏俄建立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-b977ebe1",
    title: "巴黎和会召开",
    year: 1919,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "巴黎和会召开",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-835af4e9",
    title: "新民主主义革命开端",
    year: 1919,
    track: "china",
    category: "战争",
    place: "中国",
    summary: "新民主主义革命开端",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-893de13c",
    title: "巴黎和会",
    year: 1919,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "巴黎和会",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-2e19e530",
    title: "中国共产党成立",
    year: 1921,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "中国共产党成立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-77912161",
    title: "华盛顿会议",
    year: 1921,
    endYear: 1922,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "华盛顿会议",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-25ff8e9b",
    title: "华盛顿体系",
    year: 1921,
    endYear: 1922,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "华盛顿体系",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-3082a8e2",
    title: "国民党一大召开",
    year: 1924,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "国民党一大召开",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-be785f1b",
    title: "国共第一次合作",
    year: 1924,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "国共第一次合作",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-923024b9",
    title: "新三民主义",
    year: 1924,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "新三民主义",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-7a2f2de1",
    title: "列宁逝世",
    year: 1924,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "列宁逝世",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-8fd388b8",
    title: "国民革命军出师北伐",
    year: 1926,
    endYear: 1927,
    track: "china",
    category: "战争",
    place: "中国",
    summary: "国民革命军出师北伐",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-ad9bacf7",
    title: "四一二政变",
    year: 1927,
    track: "china",
    category: "战争",
    place: "中国",
    summary: "四一二政变",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-811c995e",
    title: "南京国民政府成立",
    year: 1927,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "南京国民政府成立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-e830f02e",
    title: "南昌起义",
    year: 1927,
    track: "china",
    category: "战争",
    place: "中国",
    summary: "南昌起义",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-fe1d5e8d",
    title: "八七会议",
    year: 1927,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "八七会议",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-b2c7a1f0",
    title: "资本主义世界经济大危机",
    year: 1929,
    endYear: 1933,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "资本主义世界经济大危机",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-443a12b3",
    title: "日本发动九一八事变",
    year: 1931,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "日本发动九一八事变",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-a417a1f8",
    title: "九一八事变",
    year: 1931,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "九一八事变",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-4eea64c8",
    title: "局部抗战开始",
    year: 1931,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "局部抗战开始",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-f74700ea",
    title: "中华苏维埃共和国成立",
    year: 1931,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "中华苏维埃共和国成立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-1abe4f84",
    title: "罗斯福新政开始",
    year: 1933,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "罗斯福新政开始",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-0bc3181f",
    title: "希特勒上台",
    year: 1933,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "希特勒上台",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-2ca46edd",
    title: "红军长征",
    year: 1934,
    endYear: 1936,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "红军长征",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-7305e59e",
    title: "遵义会议（1935年）",
    year: 1934,
    endYear: 1936,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "遵义会议（1935年）",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-8d02736b",
    title: "意大利入侵埃塞俄比亚",
    year: 1935,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "意大利入侵埃塞俄比亚",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-7d1411f6",
    title: "西安事变和平解决",
    year: 1936,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "西安事变和平解决",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-68ddf621",
    title: "抗日民族统一战线初步形成",
    year: 1936,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "抗日民族统一战线初步形成",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-c57afb91",
    title: "西班牙内战爆发",
    year: 1936,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "西班牙内战爆发",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-a2143a33",
    title: "西班牙内战",
    year: 1936,
    endYear: 1939,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "西班牙内战",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-836dcbda",
    title: "七七事变",
    year: 1937,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "七七事变",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-63419375",
    title: "全面抗战爆发",
    year: 1937,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "全面抗战爆发",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-85fd8297",
    title: "南京大屠杀",
    year: 1937,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "南京大屠杀",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-17294544",
    title: "国共第二次合作",
    year: 1937,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "国共第二次合作",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-b8c217db",
    title: "苏联肃反运动扩大化",
    year: 1937,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "苏联肃反运动扩大化",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-54a7c6fb",
    title: "德国入侵波兰",
    year: 1939,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "德国入侵波兰",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-b7338d02",
    title: "百团大战",
    year: 1940,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "百团大战",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-bfa50a50",
    title: "德国入侵苏联",
    year: 1941,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "德国入侵苏联",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-20e15d31",
    title: "日本偷袭珍珠港",
    year: 1941,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "日本偷袭珍珠港",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-d14ca550",
    title: "太平洋战争爆发",
    year: 1941,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "太平洋战争爆发",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-91cff41f",
    title: "《联合国家宣言》发表",
    year: 1942,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "《联合国家宣言》发表",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-18a3dff4",
    title: "世界反法西斯同盟形成",
    year: 1942,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "世界反法西斯同盟形成",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-fd836804",
    title: "斯大林格勒战役胜利（二战转折点）",
    year: 1943,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "斯大林格勒战役胜利（二战转折点）",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-1d5c8fb9",
    title: "台湾光复",
    year: 1945,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "台湾光复",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-a08ee3b3",
    title: "重庆谈判",
    year: 1945,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "重庆谈判",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-9b14a0df",
    title: "雅尔塔会议",
    year: 1945,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "雅尔塔会议",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-6a9877f4",
    title: "二战结束",
    year: 1945,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "二战结束",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-1e80edb9",
    title: "波茨坦会议",
    year: 1945,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "波茨坦会议",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-5d9a3064",
    title: "全面内战爆发",
    year: 1946,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "全面内战爆发",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-dda3154f",
    title: "杜鲁门主义出台",
    year: 1947,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "杜鲁门主义出台",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-1b05faaa",
    title: "马歇尔计划",
    year: 1947,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "马歇尔计划",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-1df20f1a",
    title: "新民主主义革命胜利",
    year: 1949,
    track: "china",
    category: "战争",
    place: "中国",
    summary: "新民主主义革命胜利",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-1a4593d5",
    title: "北大西洋公约组织（北约）成立",
    year: 1949,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "北大西洋公约组织（北约）成立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-74013b1e",
    title: "德国分裂",
    year: 1949,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "德国分裂",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-644a3327",
    title: "《中苏友好同盟互助条约》",
    year: 1950,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "《中苏友好同盟互助条约》",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-a58eb42f",
    title: "土地改革开始",
    year: 1950,
    track: "china",
    category: "思想",
    place: "中国",
    summary: "土地改革开始",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-dfbe9e16",
    title: "朝鲜战争",
    year: 1950,
    endYear: 1953,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "朝鲜战争",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-7af507be",
    title: "第一个五年计划开始",
    year: 1953,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "第一个五年计划开始",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-bdc03018",
    title: "和平共处五项原则提出",
    year: 1953,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "和平共处五项原则提出",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-2525aeb7",
    title: "斯大林逝世",
    year: 1953,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "斯大林逝世",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-ff555cd4",
    title: "赫鲁晓夫上台",
    year: 1953,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "赫鲁晓夫上台",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-95f3fd4d",
    title: "第一届全国人大召开",
    year: 1954,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "第一届全国人大召开",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-649dd0a1",
    title: "《中华人民共和国宪法》颁布",
    year: 1954,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "《中华人民共和国宪法》颁布",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-5b9cd407",
    title: "日内瓦会议",
    year: 1954,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "日内瓦会议",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-c973fc1f",
    title: "华沙条约组织（华约）成立",
    year: 1955,
    track: "world",
    category: "政治",
    place: "世界",
    summary: "华沙条约组织（华约）成立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-9afb0e69",
    title: "两极格局正式形成",
    year: 1955,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "两极格局正式形成",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-5736679a",
    title: "三大改造完成",
    year: 1956,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "三大改造完成",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-4bce8f2a",
    title: "社会主义制度建立",
    year: 1956,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "社会主义制度建立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-20bcc0f4",
    title: "中共八大召开",
    year: 1956,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "中共八大召开",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-8d74c8c7",
    title: "苏共二十大",
    year: 1956,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "苏共二十大",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-bc71230f",
    title: "赫鲁晓夫\"秘密报告\"",
    year: 1956,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "赫鲁晓夫\"秘密报告\"",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-6f821a77",
    title: "苏联发射第一颗人造地球卫星",
    year: 1957,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "苏联发射第一颗人造地球卫星",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-5cdefd6f",
    title: "\"大跃进\"和人民公社化运动",
    year: 1958,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "\"大跃进\"和人民公社化运动",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-f7703b8c",
    title: "不结盟运动成立",
    year: 1961,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "不结盟运动成立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-8d785b70",
    title: "古巴导弹危机",
    year: 1962,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "古巴导弹危机",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-437a779c",
    title: "第一颗原子弹爆炸成功",
    year: 1964,
    track: "china",
    category: "科技",
    place: "中国",
    summary: "第一颗原子弹爆炸成功",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-a3f6b34d",
    title: "柏林墙修建",
    year: 1964,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "柏林墙修建",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-547b78f1",
    title: "\"文化大革命\"",
    year: 1966,
    endYear: 1976,
    track: "china",
    category: "战争",
    place: "中国",
    summary: "\"文化大革命\"",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-1e6e090d",
    title: "第三次中东战争",
    year: 1966,
    endYear: 1976,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "第三次中东战争",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-c2318767",
    title: "欧共体成立",
    year: 1967,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "欧共体成立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-0ac2397c",
    title: "欧洲共同体（欧共体）成立",
    year: 1967,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "欧洲共同体（欧共体）成立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-6850d40d",
    title: "美苏\"缓和\"",
    year: 1970,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "美苏\"缓和\"",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-75a8b4f1",
    title: "中美关系正常化",
    year: 1970,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "中美关系正常化",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-3edebb07",
    title: "中华人民共和国恢复在联合国的合法席位",
    year: 1971,
    track: "china",
    category: "政治",
    place: "中国",
    summary: "中华人民共和国恢复在联合国的合法席位",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-992276f9",
    title: "尼克松访华（中美关系正常化）",
    year: 1972,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "尼克松访华（中美关系正常化）",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-234fe5b5",
    title: "中共十一届三中全会",
    year: 1978,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "中共十一届三中全会",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-ecccf37c",
    title: "苏联入侵阿富汗",
    year: 1978,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "苏联入侵阿富汗",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-9ebd2622",
    title: "中美建交",
    year: 1979,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "中美建交",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-0771c85d",
    title: "深圳、珠海、汕头、厦门设立经济特区",
    year: 1980,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "深圳、珠海、汕头、厦门设立经济特区",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-704bec30",
    title: "中共十二大提出\"建设有中国特色的社会主义\"",
    year: 1982,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "中共十二大提出\"建设有中国特色的社会主义\"",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-7dc27e37",
    title: "戈尔巴乔夫改革开始",
    year: 1985,
    track: "world",
    category: "思想",
    place: "世界",
    summary: "戈尔巴乔夫改革开始",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-0fe639fd",
    title: "东欧剧变开始",
    year: 1989,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "东欧剧变开始",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-d7df3f53",
    title: "东欧剧变",
    year: 1989,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "东欧剧变",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-995a15ca",
    title: "柏林墙倒塌",
    year: 1989,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "柏林墙倒塌",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-c07ae8e0",
    title: "苏联解体",
    year: 1991,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "苏联解体",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-0bae7926",
    title: "两极格局结束",
    year: 1991,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "两极格局结束",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-5344d32c",
    title: "邓小平南方谈话",
    year: 1992,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "邓小平南方谈话",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-cb5ea023",
    title: "中共十四大确立社会主义市场经济体制目标",
    year: 1992,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "中共十四大确立社会主义市场经济体制目标",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-0887840c",
    title: "欧洲联盟（欧盟）正式成立",
    year: 1993,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "欧洲联盟（欧盟）正式成立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-9290adbe",
    title: "世界贸易组织（WTO）成立",
    year: 1995,
    track: "world",
    category: "交流",
    place: "世界",
    summary: "世界贸易组织（WTO）成立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-c2fcf8cb",
    title: "香港回归祖国",
    year: 1997,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "香港回归祖国",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-27a949e7",
    title: "中共十五大确立邓小平理论为党的指导思想",
    year: 1997,
    track: "china",
    category: "思想",
    place: "中国",
    summary: "中共十五大确立邓小平理论为党的指导思想",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-b7299691",
    title: "欧元启动",
    year: 1997,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "欧元启动",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-59d02a24",
    title: "北约轰炸南联盟",
    year: 1999,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "北约轰炸南联盟",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-019735e7",
    title: "澳门回归祖国",
    year: 1999,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "澳门回归祖国",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-61a31fb9",
    title: "美国发动阿富汗战争",
    year: 1999,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "美国发动阿富汗战争",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-0d9295cc",
    title: "科索沃战争",
    year: 1999,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "科索沃战争",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-39e962a6",
    title: "\"9·11\"事件",
    year: 2001,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "\"9·11\"事件",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-51339681",
    title: "上海合作组织成立",
    year: 2001,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "上海合作组织成立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-cac0053b",
    title: "阿富汗战争",
    year: 2001,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "阿富汗战争",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-a8aee1b6",
    title: "伊拉克战争",
    year: 2003,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "伊拉克战争",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-79bfd3d8",
    title: "北京奥运会成功举办",
    year: 2008,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "北京奥运会成功举办",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-6690ceee",
    title: "神舟七号载人航天飞行",
    year: 2008,
    track: "china",
    category: "科技",
    place: "中国",
    summary: "神舟七号载人航天飞行",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-0eb1ce88",
    title: "国际金融危机爆发",
    year: 2008,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "国际金融危机爆发",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-7996da2d",
    title: "国际金融危机",
    year: 2008,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "国际金融危机",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-49c6d544",
    title: "中共十八大召开",
    year: 2012,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "中共十八大召开",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-db2d4360",
    title: "提出\"中国梦\"",
    year: 2012,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "提出\"中国梦\"",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-50837361",
    title: "克里米亚危机",
    year: 2014,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "克里米亚危机",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-2b0cd849",
    title: "中共十九大召开",
    year: 2017,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "中共十九大召开",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-7625c143",
    title: "习近平新时代中国特色社会主义思想确立",
    year: 2017,
    track: "china",
    category: "思想",
    place: "中国",
    summary: "习近平新时代中国特色社会主义思想确立",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-c397cb17",
    title: "新冠肺炎疫情全球大流行",
    year: 2020,
    track: "world",
    category: "社会",
    place: "世界",
    summary: "新冠肺炎疫情全球大流行",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-7f56659c",
    title: "中国共产党成立100周年",
    year: 2021,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "中国共产党成立100周年",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-28c00ed7",
    title: "全面建成小康社会",
    year: 2021,
    track: "china",
    category: "社会",
    place: "中国",
    summary: "全面建成小康社会",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
  {
    id: "chrono-9e0b2367",
    title: "俄乌冲突爆发",
    year: 2022,
    track: "world",
    category: "战争",
    place: "世界",
    summary: "俄乌冲突爆发",
    scene: "",
    roles: [],
    question: "",
    keyPoints: [],
    evidence: [],
    impact: "",
    relatedIds: [],
  },
];

export const journeys: Journey[] = [
  {
    id: "state",
    title: "国家如何生长",
    subtitle: "从水渠到现代国际组织",
    question: "陌生人为什么愿意遵守同一套规则？",
    description: "沿着组织、制度与权利的变化，比较中国与世界不同的国家建构道路。",
    color: "#a64932",
    eventIds: ["liangzhu", "qin-unification", "roman-republic", "french-revolution", "xinhai", "un-founded"],
  },
  {
    id: "roads",
    title: "道路连接世界",
    subtitle: "丝路、运河、海洋与网络",
    question: "连接越多，世界一定越好吗？",
    description: "追踪商品、知识、人群与疾病如何沿着不同网络共同流动。",
    color: "#47796b",
    eventIds: ["silk-road", "grand-canal", "yuan-network", "black-death", "zheng-he", "internet-age"],
  },
  {
    id: "ocean",
    title: "向海而行",
    subtitle: "两种远航，两条道路",
    question: "郑和与哥伦布面对的是同一片海吗？",
    description: "比较明代远航、欧洲扩张与后来全球贸易，理解目标如何改变历史结果。",
    color: "#416b87",
    eventIds: ["song-commerce", "zheng-he", "columbus", "macartney", "opium-war", "china-wto"],
  },
  {
    id: "information",
    title: "知识如何远行",
    subtitle: "纸张、印刷、翻译与互联网",
    question: "当信息变便宜，谁获得了新的力量？",
    description: "从材料、复制、翻译到全球网络，观察知识传播如何挑战旧有权威。",
    color: "#78608b",
    eventIds: ["paper", "abbasid-baghdad", "movable-type", "reformation", "scientific-revolution", "internet-age"],
  },
  {
    id: "modern",
    title: "被机器改变的世界",
    subtitle: "工业、帝国与救亡图存",
    question: "技术差距为什么会变成国家命运？",
    description: "把工业革命放回中国近代史，理解冲击、回应、革命与新秩序之间的关系。",
    color: "#9a6237",
    eventIds: ["industrial-revolution", "macartney", "opium-war", "self-strengthening", "meiji-restoration", "xinhai"],
  },
];

export const eventById = new Map(events.map((event) => [event.id, event]));

export function formatYear(year: number) {
  if (year < 0) return `公元前${Math.abs(year)}年`;
  return `${year}年`;
}

export function findPeriodForYear(year: number) {
  return periods.find((period) => year >= period.start && year <= period.end) ?? periods[periods.length - 1];
}
