export type Track = "china" | "world";
export type Category = "政治" | "思想" | "科技" | "交流" | "战争" | "社会";

export type HistoryEvent = {
  id: string;
  title: string;
  year: number;
  endYear?: number;
  track: Track;
  category: Category;
  summary: string;
  image?: string;
  acceptableYears?: number[];
};

export const events: HistoryEvent[] = [
  {
    id: "chrono-2a8aa784",
    title: "旧石器时代",
    year: -3000000,
    endYear: -10000,
    track: "china",
    category: "社会",
    summary: "元谋人、北京人、山顶洞人相继出现；使用打制石器；掌握用火技术；采集狩猎为生",
  },
  {
    id: "chrono-4358dce5",
    title: "元谋人",
    year: -1700000,
    track: "china",
    category: "社会",
    summary: "距今约170万年；中国境内已知最早的古人类；使用打制石器；可能已会用火",
  },
  {
    id: "chrono-3dcdaf43",
    title: "北京人",
    year: -700000,
    endYear: -200000,
    track: "china",
    category: "社会",
    summary: "距今约70万—20万年；保留猿人体征但能直立行走；使用天然火；打制石器",
  },
  {
    id: "chrono-85ac651a",
    title: "新石器时代",
    year: -10000,
    track: "china",
    category: "思想",
    summary: "仰韶、龙山、河姆渡文化并存；使用磨制石器；出现原始农业；定居村落形成",
  },
  {
    id: "chrono-ac14fe8d",
    title: "原始农业出现",
    year: -10000,
    track: "china",
    category: "社会",
    summary: "从采集狩猎转向农耕定居；南稻北粟格局初现；推动人口增长与社会分工",
  },
  {
    id: "chrono-098d389f",
    title: "仰韶文化、大汶口文化、河姆渡文化",
    year: -7000,
    endYear: -5000,
    track: "china",
    category: "社会",
    summary: "距今约7000—5000年；黄河流域彩陶文化；长江流域水稻栽培；南北农业各具特色",
  },
  {
    id: "chrono-0845c3b1",
    title: "龙山文化、红山文化、良渚文化",
    year: -5000,
    track: "china",
    category: "社会",
    summary: "距今约5000年；黑陶文化；玉器文明；早期国家雏形出现",
  },
  {
    id: "chrono-e00331df",
    title: "两河流域出现城市国家（苏美尔文明）",
    year: -3500,
    track: "world",
    category: "社会",
    summary: "苏美尔人建立城邦；发明楔形文字；制定成文法；两河文明起源",
  },
  {
    id: "chrono-bf9640ac",
    title: "埃及统一，早王朝时期开始",
    year: -3100,
    track: "world",
    category: "政治",
    summary: "上下埃及完成统一；建立法老专制统治；古埃及文明奠基",
  },
  {
    id: "chrono-b8bf41c9",
    title: "苏美尔城市国家兴起",
    year: -2900,
    track: "world",
    category: "社会",
    summary: "约前2900年；两河流域南部出现一系列城邦；发明楔形文字；制定成文法",
  },
  {
    id: "chrono-61314a1c",
    title: "禹建立夏朝（中国第一个奴隶制王朝）",
    year: -2070,
    track: "china",
    category: "政治",
    summary: "禹建立夏朝；中国首个奴隶制王朝；王位世袭制取代禅让制；早期国家形成",
  },
  {
    id: "chrono-4c7db84f",
    title: "古巴比伦王国汉谟拉比即位",
    year: -1792,
    track: "world",
    category: "社会",
    summary: "汉谟拉比统一两河流域；实行君主专制；颁布成文法典",
  },
  {
    id: "chrono-1c19de6d",
    title: "商汤灭夏，建立商朝",
    year: -1600,
    track: "china",
    category: "政治",
    summary: "商汤灭夏建商；鸣条之战夏亡；确立王朝更替模式",
  },
  {
    id: "chrono-b06a67b1",
    title: "甲骨文、青铜文明",
    year: -1600,
    track: "china",
    category: "社会",
    summary: "甲骨文为成熟文字系统；青铜铸造技术发达；商代文明标志",
  },
  {
    id: "chrono-d2641cd8",
    title: "雅利安人入侵印度",
    year: -1500,
    track: "world",
    category: "战争",
    summary: "雅利安人侵入南亚次大陆；征服土著居民；推动吠陀文明形成",
  },
  {
    id: "chrono-1fd6d49a",
    title: "种姓制度形成",
    year: -1500,
    track: "world",
    category: "政治",
    summary: "婆罗门、刹帝利、吠舍、首陀罗四级分立；职业世袭；等级固化；影响深远",
  },
  {
    id: "chrono-2fd07ba2",
    title: "武王伐纣，西周建立",
    year: -1046,
    track: "china",
    category: "政治",
    summary: "牧野之战商亡周兴；分封宗族功臣；开创礼乐文明",
  },
  {
    id: "chrono-7d260516",
    title: "分封制、宗法制、礼乐制",
    year: -1046,
    track: "china",
    category: "社会",
    summary: "分封制封建诸侯；宗法制确立嫡长子继承；礼乐制规范等级秩序；三者互为表里",
  },
  {
    id: "chrono-5cb20adc",
    title: "第一届古代奥林匹克运动会",
    year: -776,
    track: "world",
    category: "社会",
    summary: "古希腊举办首届奥运会；奥林匹亚成为竞技中心；希腊文明象征",
  },
  {
    id: "chrono-b11a8253",
    title: "平王东迁洛邑，东周开始（春秋时期）",
    year: -770,
    track: "china",
    category: "社会",
    summary: "周平王迁都洛邑；东周开始；王室衰微；诸侯争霸局面形成",
  },
  {
    id: "chrono-614e9ae5",
    title: "恒河流域国家产生",
    year: -600,
    track: "world",
    category: "社会",
    summary: "前6世纪；恒河流域出现一系列国家；印度进入列国时代；佛教孕育",
  },
  {
    id: "chrono-5c65e028",
    title: "波斯帝国兴起",
    year: -550,
    track: "world",
    category: "政治",
    summary: "前6世纪；居鲁士建立波斯帝国；地跨亚非欧三大洲；实行行省制度",
  },
  {
    id: "chrono-410b5d44",
    title: "克利斯提尼改革",
    year: -508,
    track: "world",
    category: "思想",
    summary: "确立地域部落制度；实行陶片放逐法；推动雅典民主政治发展",
  },
  {
    id: "chrono-c69a78b5",
    title: "战国时期开始",
    year: -475,
    track: "china",
    category: "社会",
    summary: "三家分晋；战国七雄并立；兼并战争加剧；变法图强成为潮流",
  },
  {
    id: "chrono-8a359f7b",
    title: "铁器牛耕推广",
    year: -475,
    track: "china",
    category: "社会",
    summary: "铁制农具普及；牛耕推广使用；生产力显著提高；推动土地私有化",
  },
  {
    id: "chrono-ce54e866",
    title: "希波战争结束",
    year: -449,
    track: "world",
    category: "战争",
    summary: "希腊战胜波斯；保障城邦独立；希腊文明进入繁荣期",
  },
  {
    id: "chrono-3db7618b",
    title: "《卡里阿斯和约》",
    year: -449,
    track: "world",
    category: "社会",
    summary: "希波战争终结；波斯承认希腊城邦自治；希腊进入黄金时代",
  },
  {
    id: "chrono-38b6bbd8",
    title: "伯罗奔尼撒战争",
    year: -431,
    endYear: -404,
    track: "world",
    category: "战争",
    summary: "雅典与斯巴达争霸；希腊城邦由盛转衰；为马其顿崛起创造条件",
  },
  {
    id: "chrono-0560c84c",
    title: "商鞅变法",
    year: -356,
    track: "china",
    category: "思想",
    summary: "废井田开阡陌；奖励耕战；废除世卿世禄；推行县制；秦国富国强兵；为统一奠基",
  },
  {
    id: "chrono-7b8bb0cb",
    title: "亚历山大帝国建立",
    year: -330,
    track: "world",
    category: "战争",
    summary: "前4世纪晚期；亚历山大入侵波斯；建立地跨亚非欧大帝国；东西方文化交融",
  },
  {
    id: "chrono-14e0cae5",
    title: "万年 人类在非洲出现",
    year: -300,
    track: "world",
    category: "社会",
    summary: "人类起源于非洲；从能人到智人演化；旧石器时代开启",
  },
  {
    id: "chrono-28e6019c",
    title: "统一文字、货币、度量衡",
    year: -221,
    track: "china",
    category: "政治",
    summary: "秦始皇统一六国；推行郡县制；统一文字货币度量衡；建立中央集权制度；开创大一统格局",
  },
  {
    id: "chrono-cd7b8082",
    title: "刘邦建立西汉",
    year: -206,
    track: "china",
    category: "政治",
    summary: "刘邦灭项羽建汉；定都长安；沿用秦制；开启四百年汉室基业",
  },
  {
    id: "chrono-a12a7aa5",
    title: "休养生息",
    year: -206,
    track: "china",
    category: "社会",
    summary: "轻徭薄赋；与民休息；恢复社会经济；稳定新生政权",
  },
  {
    id: "chrono-af2f79a2",
    title: "古巴比伦王国汉谟拉比颁布法典",
    year: -18,
    track: "world",
    category: "社会",
    summary: "编纂成文法典；维护社会等级秩序；现存最早的较为完整的成文法典",
  },
  {
    id: "chrono-78fd8856",
    title: "希腊城邦兴起",
    year: -8,
    track: "world",
    category: "社会",
    summary: "小国寡民的城邦普遍建立；公民政治发展；海外殖民扩张；希腊文明奠基",
  },
  {
    id: "chrono-b7fc4d42",
    title: "荷马时代结束",
    year: -8,
    track: "world",
    category: "社会",
    summary: "希腊从黑暗时代走出；城邦文明即将兴起；口头史诗传承文化记忆",
  },
  {
    id: "chrono-ec0f23eb",
    title: "伯里克利时代",
    year: -5,
    track: "world",
    category: "社会",
    summary: "雅典民主政治鼎盛；公民大会权力最高；奴隶制经济繁荣；文化成就辉煌",
  },
  {
    id: "chrono-a708588f",
    title: "罗马征服意大利半岛",
    year: -3,
    track: "world",
    category: "战争",
    summary: "罗马逐步统一意大利；建立罗马同盟体系；为海外扩张奠定基础",
  },
  {
    id: "chrono-e603a19b",
    title: "罗马征服地中海地区",
    year: -2,
    track: "world",
    category: "战争",
    summary: "击败迦太基征服东地中海；成为地中海霸主；奴隶制经济繁荣",
  },
  {
    id: "chrono-790c3148",
    title: "布匿战争",
    year: -2,
    track: "world",
    category: "战争",
    summary: "罗马与迦太基争夺地中海；三次战争罗马获胜；迦太基被毁；罗马崛起为霸主",
  },
  {
    id: "chrono-09c1b066",
    title: "万年 农业革命开始（西亚两河流域）",
    year: -1,
    track: "world",
    category: "战争",
    summary: "西亚率先驯化小麦大麦；从食物采集转向食物生产；推动人类定居与社会复杂化",
  },
  {
    id: "chrono-b3bee333",
    title: "基督教在巴勒斯坦产生",
    year: -1,
    track: "world",
    category: "社会",
    summary: "耶稣创立基督教；传播平等救赎理念；后成为罗马国教；影响西方文明深远",
  },
  {
    id: "chrono-0809182c",
    title: "阿拉伯帝国崛起",
    year: 8,
    track: "world",
    category: "政治",
    summary: "穆罕默德创立伊斯兰教；阿拉伯半岛统一；建立政教合一国家",
  },
  {
    id: "chrono-d5a2cedb",
    title: "阿拉伯帝国地跨亚非欧三大洲",
    year: 8,
    track: "world",
    category: "政治",
    summary: "帝国疆域鼎盛；控制欧亚贸易要道；传播伊斯兰文明；促进东西方文化交流",
  },
  {
    id: "chrono-55c9f994",
    title: "王莽夺权，新朝建立",
    year: 9,
    track: "china",
    category: "政治",
    summary: "公元9年；外戚王莽篡汉建立新朝；西汉灭亡；推行托古改制",
  },
  {
    id: "chrono-90c594a0",
    title: "绿林军推翻王莽",
    year: 23,
    track: "china",
    category: "战争",
    summary: "23年；绿林军攻入长安；王莽被杀；新朝覆灭；更始帝立",
  },
  {
    id: "chrono-1266f378",
    title: "东汉建立",
    year: 25,
    track: "china",
    category: "政治",
    summary: "刘秀重建汉室；定都洛阳；沿用西汉制度；社会逐步恢复",
  },
  {
    id: "chrono-1e2a15a2",
    title: "光武中兴",
    year: 25,
    track: "china",
    category: "社会",
    summary: "轻徭薄赋；释放奴婢；整顿吏治；社会安定经济恢复",
  },
  {
    id: "chrono-62c630b2",
    title: "黄巾大起义",
    year: 184,
    track: "china",
    category: "社会",
    summary: "184年；张角领导太平道起义；动摇东汉统治基础；军阀割据开端",
  },
  {
    id: "chrono-dfc19d6e",
    title: "曹丕建魏，东汉灭亡",
    year: 220,
    track: "china",
    category: "社会",
    summary: "曹丕代汉建魏；东汉灭亡；三国鼎立局面形成",
  },
  {
    id: "chrono-a6e777da",
    title: "刘备称帝，蜀国建立",
    year: 221,
    track: "china",
    category: "政治",
    summary: "221年；刘备在成都称帝；国号汉；三国鼎立之一",
  },
  {
    id: "chrono-74bd7d95",
    title: "孙权称帝，吴国建立",
    year: 229,
    track: "china",
    category: "政治",
    summary: "229年；孙权在建业称帝；三国鼎立格局正式形成",
  },
  {
    id: "chrono-761c9559",
    title: "曹魏灭蜀",
    year: 263,
    track: "china",
    category: "战争",
    summary: "263年；司马昭派钟会邓艾伐蜀；蜀后主投降；蜀亡",
  },
  {
    id: "chrono-6cee3200",
    title: "司马炎代魏，西晋建立",
    year: 266,
    track: "china",
    category: "政治",
    summary: "266年；司马炎逼迫魏帝禅让；建立西晋；三国时代结束",
  },
  {
    id: "chrono-7b836a46",
    title: "西晋短暂统一",
    year: 280,
    track: "china",
    category: "政治",
    summary: "西晋灭吴完成统一；统一局面短暂；很快陷入八王之乱",
  },
  {
    id: "chrono-b17344f3",
    title: "西晋灭吴，统一全国",
    year: 280,
    track: "china",
    category: "政治",
    summary: "280年；西晋灭东吴；结束三国分裂；实现短暂统一",
  },
  {
    id: "chrono-32b9874e",
    title: "米兰敕令",
    year: 313,
    track: "world",
    category: "社会",
    summary: "罗马皇帝颁布敕令；承认基督教合法地位；基督教传播加速",
  },
  {
    id: "chrono-034115bd",
    title: "基督教合法化",
    year: 313,
    track: "world",
    category: "社会",
    summary: "基督教获得合法地位；教会势力扩张；为后来成为国教铺路",
  },
  {
    id: "chrono-cd3c4862",
    title: "西晋灭亡",
    year: 316,
    track: "china",
    category: "战争",
    summary: "316年；匈奴攻破长安；晋愍帝投降；西晋覆灭；北方进入十六国",
  },
  {
    id: "chrono-63bf9bea",
    title: "东晋建立",
    year: 317,
    track: "china",
    category: "政治",
    summary: "司马睿建立东晋；偏安江南；北方陷入十六国混战",
  },
  {
    id: "chrono-940e2072",
    title: "北方十六国",
    year: 317,
    track: "china",
    category: "社会",
    summary: "北方各民族纷纷建国；政权更迭频繁；民族大交融加速",
  },
  {
    id: "chrono-2ee094c1",
    title: "笈多帝国兴起",
    year: 320,
    track: "world",
    category: "社会",
    summary: "4世纪初；笈多帝国在恒河中游兴起；印度古典文化黄金时代；印度教复兴",
  },
  {
    id: "chrono-8dfe1478",
    title: "淝水之战",
    year: 383,
    track: "china",
    category: "战争",
    summary: "383年；东晋谢安谢玄以少胜多；前秦苻坚大败；北方再度分裂",
  },
  {
    id: "chrono-919bc4c1",
    title: "阿克苏姆王国鼎盛",
    year: 400,
    track: "world",
    category: "社会",
    summary: "4世纪；东非阿克苏姆王国进入鼎盛；控制红海贸易；基督教传入",
  },
  {
    id: "chrono-477d19fa",
    title: "刘裕建宋，南朝开始",
    year: 420,
    track: "china",
    category: "政治",
    summary: "420年；刘裕废晋恭帝；建立刘宋；南朝开端",
  },
  {
    id: "chrono-627bacdf",
    title: "北魏统一北方",
    year: 439,
    track: "china",
    category: "政治",
    summary: "北魏统一北方；结束北方长期分裂；为民族交融创造条件",
  },
  {
    id: "chrono-9371f72f",
    title: "欧洲进入中世纪",
    year: 476,
    track: "world",
    category: "社会",
    summary: "西罗马帝国灭亡；欧洲进入中世纪；封建制度逐步确立",
  },
  {
    id: "chrono-b269cff8",
    title: "北魏孝文帝迁都洛阳",
    year: 494,
    track: "china",
    category: "政治",
    summary: "494年；孝文帝从平城迁都洛阳；推行汉化改革；促进民族交融",
  },
  {
    id: "chrono-2bee9180",
    title: "查士丁尼法典编纂",
    year: 529,
    track: "world",
    category: "社会",
    summary: "查士丁尼主持编纂法典；系统整理罗马法；奠定大陆法系基础",
  },
  {
    id: "chrono-22a724d8",
    title: "隋朝建立",
    year: 581,
    track: "china",
    category: "政治",
    summary: "杨坚代周建隋；结束长期分裂；开创统一新局面",
  },
  {
    id: "chrono-ef8c0844",
    title: "隋灭陈，统一全国",
    year: 589,
    track: "china",
    category: "政治",
    summary: "隋灭陈完成统一；结束近三百年分裂；南北重新合为一体",
  },
  {
    id: "chrono-61e4c314",
    title: "唐朝建立",
    year: 618,
    track: "china",
    category: "政治",
    summary: "李渊代隋建唐；定都长安；开启大唐盛世",
  },
  {
    id: "chrono-11bc1002",
    title: "贞观之治、开元盛世",
    year: 618,
    track: "china",
    category: "社会",
    summary: "贞观之治奠定基业；开元盛世达到鼎盛；政治清明经济繁荣；文化辉煌对外开放",
  },
  {
    id: "chrono-41676a06",
    title: "穆罕默德出走麦地那，伊斯兰教创立",
    year: 622,
    track: "world",
    category: "社会",
    summary: "穆罕默德出走麦地那；创立伊斯兰教；建立政教合一社团；伊斯兰历元年",
  },
  {
    id: "chrono-1a2f1f49",
    title: "贞观之治",
    year: 627,
    endYear: 649,
    track: "china",
    category: "社会",
    summary: "唐太宗励精图治；政治清明；经济恢复；社会安定；为盛世奠基",
  },
  {
    id: "chrono-752e7a31",
    title: "新罗统一朝鲜半岛",
    year: 627,
    track: "world",
    category: "社会",
    summary: "7世纪末；新罗统一朝鲜半岛；仿唐建立中央集权国家；引入中国制度文化",
  },
  {
    id: "chrono-ee50909b",
    title: "日本大化改新",
    year: 646,
    track: "world",
    category: "社会",
    summary: "日本仿效唐制改革；建立中央集权国家；推动封建化进程",
  },
  {
    id: "chrono-5443f648",
    title: "安史之乱",
    year: 755,
    endYear: 763,
    track: "china",
    category: "社会",
    summary: "安禄山史思明叛乱；唐朝由盛转衰；藩镇割据局面形成",
  },
  {
    id: "chrono-0afd1e31",
    title: "唐朝由盛转衰",
    year: 755,
    endYear: 763,
    track: "china",
    category: "社会",
    summary: "安史之乱爆发；中央权威衰落；藩镇割据形成；唐朝由盛转衰",
  },
  {
    id: "chrono-7201b454",
    title: "查理曼帝国建立",
    year: 800,
    track: "world",
    category: "政治",
    summary: "查理曼加冕称帝；建立加洛林帝国；推动欧洲封建化",
  },
  {
    id: "chrono-ff899167",
    title: "查理曼加冕称帝",
    year: 800,
    track: "world",
    category: "社会",
    summary: "教皇为查理曼加冕；标志东西罗马帝国分野；政教关系复杂化",
  },
  {
    id: "chrono-b18111ae",
    title: "黄巢起义",
    year: 875,
    track: "china",
    category: "社会",
    summary: "875年；黄巢领导农民大起义；攻入长安；唐朝统治瓦解",
  },
  {
    id: "chrono-96dfd42c",
    title: "唐朝灭亡，五代开始",
    year: 907,
    track: "china",
    category: "政治",
    summary: "907年；朱温废唐哀帝；唐朝灭亡；五代十国开始",
  },
  {
    id: "chrono-033ae1fd",
    title: "契丹耶律阿保机建国",
    year: 916,
    track: "china",
    category: "政治",
    summary: "916年；耶律阿保机称帝；建立契丹国（后改辽）；北方游牧民族政权",
  },
  {
    id: "chrono-7efb2362",
    title: "中央集权加强",
    year: 960,
    track: "china",
    category: "社会",
    summary: "赵匡胤陈桥兵变；建立北宋；结束五代十国分裂；加强中央集权",
  },
  {
    id: "chrono-33c8b498",
    title: "西欧城市兴起",
    year: 1000,
    endYear: 1100,
    track: "world",
    category: "社会",
    summary: "10—11世纪；西欧城市逐渐兴起；市民阶层形成；推动商业复兴",
  },
  {
    id: "chrono-e8f709d2",
    title: "元昊建立西夏",
    year: 1038,
    track: "china",
    category: "政治",
    summary: "1038年；党项族李元昊称帝；建立西夏；与宋辽形成三足鼎立",
  },
  {
    id: "chrono-dececcc3",
    title: "基督教东西教会大分裂",
    year: 1054,
    track: "world",
    category: "社会",
    summary: "基督教正式分裂为天主教与东正教；东西教会分道扬镳；影响欧洲宗教格局",
  },
  {
    id: "chrono-368017ee",
    title: "王安石变法",
    year: 1069,
    track: "china",
    category: "思想",
    summary: "王安石推行新法；理财整军；意在富国强兵；因反对派阻挠成效有限",
  },
  {
    id: "chrono-7e617e08",
    title: "完颜阿骨打建立金朝",
    year: 1115,
    track: "china",
    category: "政治",
    summary: "1115年；女真族完颜阿骨打称帝；建立金朝；随后灭辽攻宋",
  },
  {
    id: "chrono-0d7707bb",
    title: "金灭辽，灭北宋（靖康之变）",
    year: 1125,
    track: "china",
    category: "社会",
    summary: "金朝先后灭辽与北宋；靖康之变；宋室南渡；南北对峙形成",
  },
  {
    id: "chrono-c00d6329",
    title: "金灭北宋，南宋开始",
    year: 1127,
    track: "china",
    category: "战争",
    summary: "1127年；金兵俘虏徽钦二帝；靖康之变；北宋灭亡；赵构建立南宋",
  },
  {
    id: "chrono-7fc8f653",
    title: "南宋与金订立绍兴和议",
    year: 1141,
    track: "china",
    category: "社会",
    summary: "1141年；南宋向金称臣纳贡；划定淮水为界；宋金对峙格局形成",
  },
  {
    id: "chrono-854645fb",
    title: "铁木真建立蒙古汗国",
    year: 1206,
    track: "china",
    category: "政治",
    summary: "1206年；铁木真统一蒙古各部；称成吉思汗；建立蒙古汗国",
  },
  {
    id: "chrono-2bdb962b",
    title: "英国《大宪章》",
    year: 1215,
    track: "world",
    category: "社会",
    summary: "英王被迫签署《大宪章》；限制王权；保障贵族权利；奠定宪政基础",
  },
  {
    id: "chrono-39215793",
    title: "马可·波罗来华",
    year: 1271,
    track: "world",
    category: "交流",
    summary: "马可·波罗经陆路来华；游历中国十余年；促进东西方交流；后著游记传播东方知识",
  },
  {
    id: "chrono-772ccd16",
    title: "元朝建立",
    year: 1271,
    track: "china",
    category: "政治",
    summary: "忽必烈定国号为元；建立元朝；继承蒙古帝国正统",
  },
  {
    id: "chrono-2cd935f6",
    title: "元灭南宋，统一全国",
    year: 1279,
    track: "china",
    category: "政治",
    summary: "元灭南宋完成统一；结束长期分裂；多民族国家重新统一",
  },
  {
    id: "chrono-03aaa3c0",
    title: "马可·波罗返回威尼斯",
    year: 1295,
    track: "world",
    category: "交流",
    summary: "马可·波罗返回威尼斯；口述东方见闻；推动欧洲对东方的认知与向往",
  },
  {
    id: "chrono-4af668e3",
    title: "元末农民起义",
    year: 1351,
    track: "china",
    category: "社会",
    summary: "1351年；红巾军起义爆发；朱元璋参加起义；元朝统治动摇",
  },
  {
    id: "chrono-343076ad",
    title: "废丞相、设内阁",
    year: 1368,
    track: "china",
    category: "社会",
    summary: "朱元璋废丞相；六部直接对皇帝负责；设内阁为辅政机构；皇权空前加强",
  },
  {
    id: "chrono-29a1e53e",
    title: "郑和七下西洋",
    year: 1405,
    endYear: 1433,
    track: "china",
    category: "交流",
    summary: "1405—1433年；郑和率船队七次下西洋；最远到达东非；世界航海史壮举",
  },
  {
    id: "chrono-f5b72f96",
    title: "明成祖迁都北京",
    year: 1421,
    track: "china",
    category: "社会",
    summary: "明成祖迁都北京；加强北方防御；天子守国门；巩固统一",
  },
  {
    id: "chrono-f948d265",
    title: "奥斯曼帝国攻陷君士坦丁堡",
    year: 1453,
    track: "world",
    category: "政治",
    summary: "奥斯曼帝国攻陷君士坦丁堡；东罗马帝国灭亡；阻断东西方陆路贸易；推动地理大发现",
  },
  {
    id: "chrono-6bef179b",
    title: "迪亚士到达好望角",
    year: 1487,
    track: "world",
    category: "社会",
    summary: "迪亚士抵达好望角；开辟绕过非洲南端航线；为大航海时代奠基",
  },
  {
    id: "chrono-028cdf99",
    title: "哥伦布到达美洲",
    year: 1492,
    track: "world",
    category: "交流",
    summary: "1492年；哥伦布率船队横渡大西洋；到达美洲；新航路开辟；全球联系建立",
  },
  {
    id: "chrono-52859407",
    title: "达·伽马到达印度",
    year: 1497,
    track: "world",
    category: "社会",
    summary: "达·伽马绕过好望角抵达印度；开辟欧洲至亚洲海上航线；推动世界市场形成",
  },
  {
    id: "chrono-0b2eaa94",
    title: "西班牙和葡萄牙形成",
    year: 1500,
    track: "world",
    category: "政治",
    summary: "15世纪末；西班牙和葡萄牙完成统一；率先走上殖民扩张道路",
  },
  {
    id: "chrono-37a409fe",
    title: "近代科学革命",
    year: 1500,
    endYear: 1700,
    track: "world",
    category: "科技",
    summary: "16—17世纪；哥白尼日心说到牛顿经典力学；科学方法确立；人类认识宇宙",
  },
  {
    id: "chrono-f4d742ad",
    title: "桑海帝国鼎盛",
    year: 1500,
    track: "world",
    category: "社会",
    summary: "16世纪；西非桑海帝国进入鼎盛；控制跨撒哈拉贸易；伊斯兰文化繁荣",
  },
  {
    id: "chrono-dfb987e8",
    title: "葡萄牙人占据澳门（租居）",
    year: 1510,
    track: "china",
    category: "社会",
    summary: "葡萄牙人租居澳门；西方势力首次渗入中国沿海；中西接触开始",
  },
  {
    id: "chrono-62f3a667",
    title: "马丁·路德发表《九十五条论纲》",
    year: 1517,
    track: "world",
    category: "社会",
    summary: "马丁·路德发表《九十五条论纲》；掀起宗教改革运动；打破天主教垄断；推动民族国家发展",
  },
  {
    id: "chrono-ad5566b6",
    title: "麦哲伦船队环球航行",
    year: 1519,
    endYear: 1522,
    track: "world",
    category: "社会",
    summary: "麦哲伦船队完成首次环球航行；证明地圆说；世界真正连为一体；推动全球贸易",
  },
  {
    id: "chrono-4a9d7031",
    title: "葡萄牙人取得澳门居住权",
    year: 1553,
    track: "china",
    category: "社会",
    summary: "葡萄牙人取得澳门居住权；沿海主权逐步受损；西方势力渗透加深",
  },
  {
    id: "chrono-61d6d7f6",
    title: "隆庆开关，月港成为合法对外贸易港",
    year: 1567,
    track: "china",
    category: "交流",
    summary: "隆庆帝开放月港通商；民间海外贸易合法化；白银大量流入；推动商品经济发展",
  },
  {
    id: "chrono-d03c5ba4",
    title: "英国击败西班牙无敌舰队",
    year: 1588,
    track: "world",
    category: "社会",
    summary: "英国击败西班牙无敌舰队；海上霸权转移；为殖民扩张奠定基础",
  },
  {
    id: "chrono-71d15c92",
    title: "启蒙运动",
    year: 1600,
    endYear: 1800,
    track: "world",
    category: "思想",
    summary: "17—18世纪；理性主义兴起；伏尔泰卢梭孟德斯鸠；推动社会变革",
  },
  {
    id: "chrono-9b08f952",
    title: "后金建立",
    year: 1616,
    track: "china",
    category: "政治",
    summary: "努尔哈赤建立后金；与明朝对抗；奠定清朝基业",
  },
  {
    id: "chrono-b20b46b8",
    title: "皇太极改国号为清",
    year: 1636,
    track: "china",
    category: "社会",
    summary: "皇太极改国号为清；完善政权制度；为入关统一做准备",
  },
  {
    id: "chrono-a4ca0f48",
    title: "英国资产阶级革命开始",
    year: 1640,
    track: "world",
    category: "战争",
    summary: "英国资产阶级革命爆发；议会与国王对抗；推翻封建专制；开辟资产阶级革命时代",
  },
  {
    id: "chrono-7957654a",
    title: "英国资产阶级革命爆发",
    year: 1640,
    track: "world",
    category: "政治",
    summary: "1640年；英国议会与国王决裂；资产阶级革命爆发；开启近代政治变革",
  },
  {
    id: "chrono-cf130c3f",
    title: "清军入关，明朝灭亡",
    year: 1644,
    track: "china",
    category: "社会",
    summary: "清军入关；明朝灭亡；清朝确立全国统治",
  },
  {
    id: "chrono-eac7785a",
    title: "马斯顿荒原战役",
    year: 1644,
    track: "world",
    category: "战争",
    summary: "1644年；英国议会军战胜王党军队；内战转折点；克伦威尔崛起",
  },
  {
    id: "chrono-28f98060",
    title: "郑成功收复台湾",
    year: 1662,
    track: "china",
    category: "社会",
    summary: "郑成功驱逐荷兰殖民者；收复台湾；维护领土主权",
  },
  {
    id: "chrono-dd3017a0",
    title: "清朝设置台湾府，隶属福建省",
    year: 1684,
    track: "china",
    category: "社会",
    summary: "清朝设置台湾府；隶属福建省；加强台湾管辖；巩固海防",
  },
  {
    id: "chrono-6178e267",
    title: "牛顿发表《自然哲学的数学原理》",
    year: 1687,
    track: "world",
    category: "思想",
    summary: "牛顿发表《自然哲学的数学原理》；建立经典力学体系；奠定近代物理学基础",
  },
  {
    id: "chrono-6cdd7790",
    title: "英国光荣革命",
    year: 1688,
    track: "world",
    category: "战争",
    summary: "英国光荣革命；不流血完成政权更迭；为君主立宪制铺路",
  },
  {
    id: "chrono-c94d3bf1",
    title: "中俄签订《尼布楚条约》",
    year: 1689,
    track: "china",
    category: "政治",
    summary: "中俄签订《尼布楚条约》；划定东段边界；维护领土主权；中国首个平等边界条约",
  },
  {
    id: "chrono-6fb40409",
    title: "英国颁布《权利法案》",
    year: 1689,
    track: "world",
    category: "社会",
    summary: "英国颁布《权利法案》；限制王权；确立议会至上原则；君主立宪制确立",
  },
  {
    id: "chrono-1a4aaea2",
    title: "清朝设置驻藏大臣",
    year: 1727,
    track: "china",
    category: "社会",
    summary: "清朝设置驻藏大臣；加强西藏管辖；巩固统一多民族国家",
  },
  {
    id: "chrono-8a34478f",
    title: "第一次工业革命",
    year: 1750,
    endYear: 1850,
    track: "world",
    category: "科技",
    summary: "18世纪中期到19世纪中期；蒸汽机发明；机器大生产取代手工；工厂制度确立",
  },
  {
    id: "chrono-efc78418",
    title: "清朝仅留广州一口通商",
    year: 1757,
    track: "china",
    category: "交流",
    summary: "清朝实行广州一口通商；限制对外贸易；闭关锁国政策深化",
  },
  {
    id: "chrono-a8f2ddf4",
    title: "清朝设立伊犁将军",
    year: 1762,
    track: "china",
    category: "政治",
    summary: "1762年；清朝设立伊犁将军；管辖新疆地区；巩固西北边疆",
  },
  {
    id: "chrono-035ee994",
    title: "美国独立战争",
    year: 1775,
    endYear: 1783,
    track: "world",
    category: "战争",
    summary: "北美独立战争爆发；反抗英国殖民统治；争取民族独立",
  },
  {
    id: "chrono-390661db",
    title: "《独立宣言》",
    year: 1775,
    endYear: 1783,
    track: "world",
    category: "社会",
    summary: "北美发表《独立宣言》；宣告人人平等；提出主权在民；推动资产阶级民主思想传播",
  },
  {
    id: "chrono-dbdca223",
    title: "美国制定宪法",
    year: 1787,
    track: "world",
    category: "政治",
    summary: "1787年；美国制宪会议通过联邦宪法；确立三权分立；共和制确立",
  },
  {
    id: "chrono-79847136",
    title: "《人权宣言》",
    year: 1789,
    track: "world",
    category: "社会",
    summary: "法国颁布《人权宣言》；宣告人权与公民权；提出主权在民；奠定法国民主基石",
  },
  {
    id: "chrono-5e8338b3",
    title: "清朝颁布治理西藏章程",
    year: 1793,
    track: "china",
    category: "政治",
    summary: "1793年；颁布《钦定藏内善后章程》；确立金瓶掣签制度；加强西藏管辖",
  },
  {
    id: "chrono-03d5abf3",
    title: "拿破仑称帝",
    year: 1804,
    track: "world",
    category: "社会",
    summary: "拿破仑加冕称帝；建立法兰西第一帝国；颁布《拿破仑法典》；巩固革命成果",
  },
  {
    id: "chrono-f9eca749",
    title: "法兰西第一帝国",
    year: 1804,
    track: "world",
    category: "政治",
    summary: "拿破仑建立法兰西第一帝国；对外战争传播革命思想；动摇欧洲封建秩序",
  },
  {
    id: "chrono-3fb71475",
    title: "海地独立",
    year: 1804,
    track: "world",
    category: "政治",
    summary: "1804年；海地宣布独立；拉美第一个独立国家；推翻法国殖民统治",
  },
  {
    id: "chrono-730ff0bb",
    title: "滑铁卢战役",
    year: 1815,
    track: "world",
    category: "战争",
    summary: "滑铁卢战役拿破仑战败；法兰西第一帝国终结；欧洲旧秩序暂时恢复",
  },
  {
    id: "chrono-3540e6c6",
    title: "拿破仑帝国覆灭",
    year: 1815,
    track: "world",
    category: "政治",
    summary: "拿破仑帝国覆灭；维也纳会议召开；建立欧洲均势体系；旧势力暂时复辟",
  },
  {
    id: "chrono-3cc21eb0",
    title: "维也纳体系",
    year: 1815,
    track: "world",
    category: "社会",
    summary: "维也纳会议召开；建立大国均势体系；维持欧洲相对稳定；压制革命与民族运动",
  },
  {
    id: "chrono-d54daf42",
    title: "《南京条约》签订，中国开始沦为半殖民地半封建社会",
    year: 1840,
    endYear: 1842,
    track: "china",
    category: "政治",
    summary: "英国发动鸦片战争；清政府战败签约；中国主权遭破坏；开始沦为半殖民地半封建社会",
  },
  {
    id: "chrono-3c04055d",
    title: "中英《虎门条约》签订",
    year: 1843,
    track: "china",
    category: "社会",
    summary: "1843年；英国攫取领事裁判权；片面最惠国待遇；租界制度开端",
  },
  {
    id: "chrono-c426ec7b",
    title: "中美《望厦条约》、中法《黄埔条约》签订",
    year: 1844,
    track: "china",
    category: "社会",
    summary: "1844年；美国法国趁火打劫；攫取与英国同等特权；中国主权进一步丧失",
  },
  {
    id: "chrono-7146750b",
    title: "欧洲革命浪潮",
    year: 1848,
    track: "world",
    category: "战争",
    summary: "欧洲多国爆发革命浪潮；冲击维也纳体系；推动民族统一与民主运动",
  },
  {
    id: "chrono-995b9209",
    title: "《共产党宣言》发表",
    year: 1848,
    track: "world",
    category: "思想",
    summary: "1848年；马克思恩格斯发表《共产党宣言》；科学社会主义诞生；工人运动有了理论指导",
  },
  {
    id: "chrono-7bef6f14",
    title: "太平天国运动",
    year: 1851,
    endYear: 1864,
    track: "china",
    category: "社会",
    summary: "洪秀全发动太平天国运动；建都天京；颁布《天朝田亩制度》；沉重打击清朝统治",
  },
  {
    id: "chrono-403b3846",
    title: "克里米亚战争",
    year: 1853,
    endYear: 1856,
    track: "world",
    category: "战争",
    summary: "俄国与奥斯曼帝国争夺黑海控制权；俄国战败；暴露农奴制弊端；推动俄国改革",
  },
  {
    id: "chrono-fcb528bd",
    title: "《天津条约》《北京条约》",
    year: 1856,
    endYear: 1860,
    track: "china",
    category: "政治",
    summary: "英法联军侵华；清政府战败；签订不平等条约；主权进一步丧失",
  },
  {
    id: "chrono-35f0c1dd",
    title: "中俄《瑷珲条约》、中英/中法《天津条约》签订",
    year: 1858,
    track: "china",
    category: "社会",
    summary: "1858年；沙俄割占中国领土；英法获取更多特权；中国半殖民地化加深",
  },
  {
    id: "chrono-fe137b7e",
    title: "达尔文发表《物种起源》",
    year: 1859,
    track: "world",
    category: "科技",
    summary: "达尔文发表《物种起源》；提出生物进化论；挑战神创论；推动科学思想发展",
  },
  {
    id: "chrono-805a11cd",
    title: "中英/中法/中俄《北京条约》签订",
    year: 1860,
    track: "china",
    category: "社会",
    summary: "1860年；英法联军火烧圆明园后签约；沙俄割占更多领土；中国半殖民地化进一步加深",
  },
  {
    id: "chrono-d7c7db95",
    title: "美国内战爆发",
    year: 1861,
    track: "world",
    category: "社会",
    summary: "美国南方与北方对抗；爆发内战；最终废除奴隶制；维护国家统一",
  },
  {
    id: "chrono-189ed026",
    title: "俄国农奴制改革",
    year: 1861,
    track: "world",
    category: "思想",
    summary: "沙皇亚历山大二世推行改革；废除农奴制；推动俄国资本主义发展",
  },
  {
    id: "chrono-21b92acf",
    title: "国际工人协会成立",
    year: 1864,
    track: "world",
    category: "社会",
    summary: "1864年；第一国际在伦敦成立；马克思参与领导；国际工人运动进入新阶段",
  },
  {
    id: "chrono-033c9a05",
    title: "《资本论》第一卷问世",
    year: 1867,
    track: "world",
    category: "思想",
    summary: "1867年；马克思出版《资本论》第一卷；揭示剩余价值规律；政治经济学奠基",
  },
  {
    id: "chrono-b7abb6e3",
    title: "日本明治维新",
    year: 1868,
    track: "world",
    category: "社会",
    summary: "1868年；明治天皇推行维新；废藩置县；殖产兴业；日本走上资本主义道路",
  },
  {
    id: "chrono-6f9fcf23",
    title: "民族资本主义产生（继昌隆缫丝厂等）",
    year: 1870,
    track: "china",
    category: "社会",
    summary: "洋务运动推动下；民族资本主义企业出现；近代民族工业起步",
  },
  {
    id: "chrono-08124b7e",
    title: "普法战争",
    year: 1870,
    track: "world",
    category: "战争",
    summary: "普鲁士与法国开战；普鲁士获胜；推动德意志统一进程",
  },
  {
    id: "chrono-85389f2f",
    title: "法兰西第二帝国覆灭",
    year: 1870,
    track: "world",
    category: "政治",
    summary: "普法战争中法国战败；法兰西第二帝国覆灭；为德意志统一扫清障碍",
  },
  {
    id: "chrono-a7dff18a",
    title: "意大利统一",
    year: 1870,
    track: "world",
    category: "政治",
    summary: "1870年；意大利完成统一；教皇国缩小；民族国家建立",
  },
  {
    id: "chrono-f8d53013",
    title: "巴黎公社",
    year: 1871,
    track: "world",
    category: "社会",
    summary: "巴黎工人起义；建立巴黎公社；首次无产阶级政权尝试；影响深远",
  },
  {
    id: "chrono-28c11aee",
    title: "德意志帝国建立",
    year: 1871,
    track: "world",
    category: "政治",
    summary: "普鲁士击败法国；德意志帝国建立；完成国家统一；改变欧洲力量格局",
  },
  {
    id: "chrono-02b22d81",
    title: "苏丹爆发马赫迪大起义",
    year: 1881,
    track: "world",
    category: "战争",
    summary: "1881年；苏丹马赫迪领导反英起义；击毙戈登；非洲反殖民斗争",
  },
  {
    id: "chrono-2883b1b3",
    title: "德、奥、意三国同盟形成",
    year: 1882,
    track: "world",
    category: "社会",
    summary: "德、奥、意结成军事同盟；对抗法俄协约；欧洲两大军事集团对峙开始",
  },
  {
    id: "chrono-15878837",
    title: "埃及抗英战争",
    year: 1882,
    track: "world",
    category: "战争",
    summary: "1882年；埃及阿拉比领导抗英战争；失败后英国占领埃及；非洲殖民化加速",
  },
  {
    id: "chrono-2d48173f",
    title: "中法战争",
    year: 1883,
    endYear: 1885,
    track: "china",
    category: "战争",
    summary: "中法战争爆发；法国不胜而胜；中国不败而败；西南门户打开",
  },
  {
    id: "chrono-94c3df39",
    title: "中法战争",
    year: 1883,
    endYear: 1885,
    track: "china",
    category: "战争",
    summary: "法国不胜而胜；中国不败而败；暴露清政府外交软弱",
  },
  {
    id: "chrono-d0b4d7f3",
    title: "巴西建立共和国",
    year: 1889,
    track: "world",
    category: "政治",
    summary: "1889年；巴西废除帝制；建立联邦共和国；拉美共和化推进",
  },
  {
    id: "chrono-ebf6135d",
    title: "甲午中日战争",
    year: 1894,
    endYear: 1895,
    track: "china",
    category: "战争",
    summary: "日本发动甲午战争；清政府战败；签订《马关条约》；民族危机加深",
  },
  {
    id: "chrono-47c3d93a",
    title: "《马关条约》",
    year: 1894,
    endYear: 1895,
    track: "china",
    category: "政治",
    summary: "清政府战败签约；割让台湾澎湖；赔偿巨款；允许设厂；半殖民地化加深",
  },
  {
    id: "chrono-b6eee02b",
    title: "台湾被割占",
    year: 1894,
    endYear: 1895,
    track: "china",
    category: "社会",
    summary: "《马关条约》割让台湾；台湾被日本殖民统治长达五十年",
  },
  {
    id: "chrono-367e3524",
    title: "美国工业产值跃居世界第一",
    year: 1894,
    track: "world",
    category: "社会",
    summary: "美国工业产值超越英国；跃居世界第一；标志世界经济重心转移",
  },
  {
    id: "chrono-40944d54",
    title: "公车上书",
    year: 1895,
    track: "china",
    category: "社会",
    summary: "康有为梁启超发动公车上书；维新派登上政治舞台；推动变法运动",
  },
  {
    id: "chrono-17174c2c",
    title: "维新思想传播",
    year: 1895,
    track: "china",
    category: "思想",
    summary: "维新思想广泛传播；主张变法图强；启发民智；为戊戌变法造舆论",
  },
  {
    id: "chrono-90c6f846",
    title: "列宁主义诞生",
    year: 1895,
    track: "world",
    category: "社会",
    summary: "列宁在俄国传播马克思主义；建立无产阶级政党雏形；推动俄国革命运动",
  },
  {
    id: "chrono-d1701dd7",
    title: "戊戌变法（百日维新）",
    year: 1898,
    track: "china",
    category: "思想",
    summary: "光绪帝颁布明定国是诏；推行变法新政；百日即遭镇压；资产阶级改良道路失败",
  },
  {
    id: "chrono-785658e7",
    title: "美西战争",
    year: 1898,
    track: "world",
    category: "战争",
    summary: "美国为夺取西班牙殖民地发动战争；标志美国走上扩张道路；跻身世界强国",
  },
  {
    id: "chrono-1b03529f",
    title: "义和团运动",
    year: 1899,
    endYear: 1900,
    track: "china",
    category: "社会",
    summary: "义和团运动兴起；反抗帝国主义侵略；后遭八国联军镇压",
  },
  {
    id: "chrono-2186fef1",
    title: "美国提出门户开放政策",
    year: 1899,
    track: "world",
    category: "社会",
    summary: "美国提出门户开放政策；要求列强利益均沾；标志美国介入中国事务",
  },
  {
    id: "chrono-bae9ca74",
    title: "八国联军侵华",
    year: 1900,
    track: "china",
    category: "战争",
    summary: "八国联军侵华；清政府战败；签订《辛丑条约》；民族危机空前严重",
  },
  {
    id: "chrono-9795030b",
    title: "德国物理学家普朗克提出量子论",
    year: 1900,
    track: "world",
    category: "科技",
    summary: "普朗克提出量子假说；打破经典物理学框架；开创量子力学新纪元",
  },
  {
    id: "chrono-65a4b945",
    title: "《辛丑条约》签订",
    year: 1901,
    track: "china",
    category: "政治",
    summary: "清政府与十一国签约；赔款巨额白银；允许驻军；中国完全沦为半殖民地半封建社会",
  },
  {
    id: "chrono-151c3457",
    title: "中国完全沦为半殖民地半封建社会",
    year: 1901,
    track: "china",
    category: "社会",
    summary: "《辛丑条约》签订后；清政府成为洋人朝廷；中国完全沦为半殖民地半封建社会",
  },
  {
    id: "chrono-2df8b3c3",
    title: "莱特兄弟发明飞机",
    year: 1903,
    track: "world",
    category: "科技",
    summary: "莱特兄弟试飞成功；人类首次实现动力飞行；开创航空时代",
  },
  {
    id: "chrono-39f98e00",
    title: "中国同盟会成立",
    year: 1905,
    track: "china",
    category: "社会",
    summary: "孙中山在日本成立同盟会；提出三民主义；推动资产阶级革命运动",
  },
  {
    id: "chrono-9da999b2",
    title: "三民主义提出",
    year: 1905,
    track: "china",
    category: "社会",
    summary: "孙中山提出民族民权民生三大主义；成为革命指导思想；推动辛亥革命",
  },
  {
    id: "chrono-3bb6fca6",
    title: "废除科举制",
    year: 1905,
    track: "china",
    category: "社会",
    summary: "清政府废除科举制度；延续千年的选官制度终结；推动新式教育发展",
  },
  {
    id: "chrono-fb870372",
    title: "爱因斯坦提出相对论",
    year: 1905,
    track: "world",
    category: "科技",
    summary: "爱因斯坦提出狭义相对论；颠覆经典时空观；开创现代物理学革命",
  },
  {
    id: "chrono-844f6a7f",
    title: "清政府预备立宪",
    year: 1906,
    track: "china",
    category: "政治",
    summary: "1906年；清政府宣布预备立宪；试图缓和革命压力；最终未能挽救清朝",
  },
  {
    id: "chrono-771833a9",
    title: "英、法、俄三国协约",
    year: 1907,
    track: "world",
    category: "社会",
    summary: "英法俄结成三国协约；对抗三国同盟；欧洲两大军事集团正式对峙",
  },
  {
    id: "chrono-53a77647",
    title: "两大军事集团形成",
    year: 1907,
    track: "world",
    category: "社会",
    summary: "三国同盟与三国协约形成；欧洲分裂为两大阵营；世界大战危机加深",
  },
  {
    id: "chrono-82565adf",
    title: "墨西哥爆发资产阶级革命",
    year: 1910,
    track: "world",
    category: "社会",
    summary: "1910年；墨西哥革命爆发；推翻迪亚斯独裁；颁布资产阶级宪法",
  },
  {
    id: "chrono-723eab0b",
    title: "推翻清朝统治",
    year: 1911,
    track: "china",
    category: "社会",
    summary: "武昌起义爆发；各省纷纷响应；清朝统治土崩瓦解",
  },
  {
    id: "chrono-c5a3498e",
    title: "清帝退位",
    year: 1912,
    track: "china",
    category: "社会",
    summary: "清帝溥仪退位；两千多年帝制终结；中华民国成立",
  },
  {
    id: "chrono-d3eee214",
    title: "《临时约法》",
    year: 1912,
    track: "china",
    category: "政治",
    summary: "南京临时政府颁布《中华民国临时约法》；确立共和制度；中国首部资产阶级宪法",
  },
  {
    id: "chrono-a9057159",
    title: "中华民国成立",
    year: 1912,
    track: "china",
    category: "政治",
    summary: "1912年1月1日；孙中山就任临时大总统；中华民国成立；两千年帝制终结",
  },
  {
    id: "chrono-375c9795",
    title: "第一次世界大战爆发",
    year: 1914,
    track: "world",
    category: "战争",
    summary: "1914年；斐迪南大公遇刺；萨拉热窝事件引发一战；马恩河战役",
  },
  {
    id: "chrono-28c49fec",
    title: "新文化运动开始（民主与科学）",
    year: 1915,
    track: "china",
    category: "思想",
    summary: "陈独秀创办《新青年》；高举民主与科学旗帜；批判封建礼教；启发青年思想",
  },
  {
    id: "chrono-7db7e699",
    title: "袁世凯复辟帝制",
    year: 1915,
    track: "china",
    category: "政治",
    summary: "1915年12月；袁世凯称帝；改中华民国为中华帝国；次年取消；不久病死",
  },
  {
    id: "chrono-002135b5",
    title: "俄国二月革命",
    year: 1917,
    track: "world",
    category: "战争",
    summary: "俄国爆发二月革命；推翻沙皇统治；为十月革命创造条件",
  },
  {
    id: "chrono-3b831007",
    title: "苏俄建立",
    year: 1917,
    track: "world",
    category: "政治",
    summary: "布尔什维克发动十月革命；建立苏维埃政权；世界上首个社会主义国家诞生",
  },
  {
    id: "chrono-cc25d9c0",
    title: "张勋复辟",
    year: 1917,
    track: "china",
    category: "政治",
    summary: "1917年6月；张勋拥立溥仪复辟；仅12天即告失败；军阀混战加剧",
  },
  {
    id: "chrono-a8043fe2",
    title: "护法运动开始",
    year: 1917,
    track: "china",
    category: "政治",
    summary: "1917年8月；孙中山发起护法运动；反对段祺瑞拒绝《临时约法》；最终失败",
  },
  {
    id: "chrono-340731b7",
    title: "俄国十月革命",
    year: 1917,
    track: "world",
    category: "政治",
    summary: "1917年；列宁领导布尔什维克武装起义；建立苏维埃政权；世界第一个社会主义国家",
  },
  {
    id: "chrono-16819704",
    title: "第一次世界大战结束",
    year: 1918,
    track: "world",
    category: "战争",
    summary: "1918年；德国投降；第一次世界大战结束；巴黎和会召开；国际格局重塑",
  },
  {
    id: "chrono-b977ebe1",
    title: "巴黎和会召开",
    year: 1919,
    track: "world",
    category: "社会",
    summary: "战胜国召开巴黎和会；重新划分势力范围；中国外交失败引发五四运动",
  },
  {
    id: "chrono-835af4e9",
    title: "新民主主义革命开端",
    year: 1919,
    track: "china",
    category: "战争",
    summary: "五四运动爆发；学生工人走上街头；反帝反封建；新民主主义革命开端",
  },
  {
    id: "chrono-893de13c",
    title: "巴黎和会",
    year: 1919,
    track: "world",
    category: "社会",
    summary: "战胜国召开巴黎和会；重新瓜分世界；建立凡尔赛体系；埋下战争隐患",
  },
  {
    id: "chrono-5f9654f6",
    title: "五四运动爆发",
    year: 1919,
    track: "china",
    category: "社会",
    summary: "1919年5月4日；巴黎和会外交失败引发；学生工人罢课罢工；新民主主义革命开端",
  },
  {
    id: "chrono-6266f082",
    title: "拉美民族民主革命与改革",
    year: 1920,
    endYear: 1940,
    track: "world",
    category: "社会",
    summary: "1920—1940年；拉美各国民族民主运动兴起；推动政治独立和经济自主",
  },
  {
    id: "chrono-2e19e530",
    title: "中国共产党成立",
    year: 1921,
    track: "china",
    category: "社会",
    summary: "中国共产党第一次全国代表大会召开；中国共产党成立；中国革命面貌焕然一新",
  },
  {
    id: "chrono-77912161",
    title: "华盛顿会议",
    year: 1921,
    endYear: 1922,
    track: "world",
    category: "社会",
    summary: "华盛顿会议召开；调整远东太平洋秩序；确立华盛顿体系",
  },
  {
    id: "chrono-25ff8e9b",
    title: "华盛顿体系",
    year: 1921,
    endYear: 1922,
    track: "world",
    category: "社会",
    summary: "华盛顿会议确立远东新秩序；限制海军军备；暂时缓和列强矛盾",
  },
  {
    id: "chrono-b47db3da",
    title: "苏俄实行新经济政策",
    year: 1921,
    track: "world",
    category: "社会",
    summary: "1921年；列宁推行新经济政策；利用市场机制恢复经济；为工业化奠基",
  },
  {
    id: "chrono-3642e325",
    title: "墨索里尼建立法西斯政权",
    year: 1922,
    track: "world",
    category: "政治",
    summary: "1922年；墨索里尼进军罗马；建立意大利法西斯政权；欧洲法西斯主义开端",
  },
  {
    id: "chrono-7db84b7f",
    title: "苏联建立",
    year: 1922,
    track: "world",
    category: "政治",
    summary: "1922年；苏维埃社会主义共和国联盟成立；第一个联邦制社会主义国家",
  },
  {
    id: "chrono-3082a8e2",
    title: "国民党一大召开",
    year: 1924,
    track: "china",
    category: "社会",
    summary: "国民党一大召开；确立联俄联共扶助农工政策；第一次国共合作形成",
  },
  {
    id: "chrono-be785f1b",
    title: "国共第一次合作",
    year: 1924,
    track: "china",
    category: "社会",
    summary: "国共两党实现第一次合作；建立革命统一战线；推动国民革命运动",
  },
  {
    id: "chrono-923024b9",
    title: "新三民主义",
    year: 1924,
    track: "china",
    category: "社会",
    summary: "孙中山重新解释三民主义；增加反帝反封建内容；成为国共合作政治基础",
  },
  {
    id: "chrono-7a2f2de1",
    title: "列宁逝世",
    year: 1924,
    track: "world",
    category: "社会",
    summary: "列宁逝世；斯大林逐步掌权；苏联进入新的建设时期",
  },
  {
    id: "chrono-8fd388b8",
    title: "国民革命军出师北伐",
    year: 1926,
    endYear: 1927,
    track: "china",
    category: "战争",
    summary: "国民革命军出师北伐；基本推翻北洋军阀统治；动摇帝国主义在华根基",
  },
  {
    id: "chrono-ad9bacf7",
    title: "四一二政变",
    year: 1927,
    track: "china",
    category: "战争",
    summary: "蒋介石发动四一二政变；大肆屠杀共产党人；第一次国共合作破裂",
  },
  {
    id: "chrono-811c995e",
    title: "南京国民政府成立",
    year: 1927,
    track: "china",
    category: "政治",
    summary: "蒋介石建立南京国民政府；形式上统一全国；实行一党专政",
  },
  {
    id: "chrono-e830f02e",
    title: "南昌起义",
    year: 1927,
    track: "china",
    category: "战争",
    summary: "周恩来等领导南昌起义；打响武装反抗国民党第一枪；人民军队诞生",
  },
  {
    id: "chrono-fe1d5e8d",
    title: "八七会议",
    year: 1927,
    track: "china",
    category: "社会",
    summary: "中共中央召开八七会议；确定土地革命和武装反抗方针；纠正右倾错误",
  },
  {
    id: "chrono-edad4f7d",
    title: "湘赣边秋收起义",
    year: 1927,
    track: "china",
    category: "战争",
    summary: "1927年9月；毛泽东领导秋收起义；后转向井冈山；开辟农村包围城市道路",
  },
  {
    id: "chrono-d11744b4",
    title: "毛泽东创建井冈山革命根据地",
    year: 1927,
    track: "china",
    category: "政治",
    summary: "1927年10月；毛泽东率部上井冈山；建立第一个农村革命根据地；工农武装割据",
  },
  {
    id: "chrono-07db2b24",
    title: "井冈山会师",
    year: 1928,
    track: "china",
    category: "政治",
    summary: "1928年4月；朱德陈毅率部上井冈山与毛泽东会师；成立红四军；壮大革命力量",
  },
  {
    id: "chrono-6b5dac61",
    title: "张学良东北易帜",
    year: 1928,
    track: "china",
    category: "政治",
    summary: "1928年12月；张学良通电服从南京国民政府；国民政府形式上统一全国",
  },
  {
    id: "chrono-b2c7a1f0",
    title: "资本主义世界经济大危机",
    year: 1929,
    endYear: 1933,
    track: "world",
    category: "社会",
    summary: "资本主义世界爆发经济大危机；生产停滞失业激增；动摇资本主义根基",
  },
  {
    id: "chrono-0421d8c0",
    title: "古田会议召开",
    year: 1929,
    track: "china",
    category: "政治",
    summary: "1929年12月；古田会议确立党对军队的绝对领导；建军原则奠基",
  },
  {
    id: "chrono-0e1160f8",
    title: "蒋介石发动围剿",
    year: 1930,
    track: "china",
    category: "战争",
    summary: "1930年10月起；蒋介石调集重兵围剿革命根据地；红军五次反围剿",
  },
  {
    id: "chrono-443a12b3",
    title: "日本发动九一八事变",
    year: 1931,
    track: "world",
    category: "社会",
    summary: "日本关东军制造九一八事变；侵占中国东北；局部抗战开始",
  },
  {
    id: "chrono-4eea64c8",
    title: "局部抗战开始",
    year: 1931,
    track: "china",
    category: "社会",
    summary: "九一八事变后东北军民奋起抵抗；中国局部抗战开始；揭开世界反法西斯战争序幕",
  },
  {
    id: "chrono-f74700ea",
    title: "中华苏维埃共和国成立",
    year: 1931,
    track: "china",
    category: "政治",
    summary: "中华苏维埃共和国在瑞金成立；建立工农民主政权；探索革命道路",
  },
  {
    id: "chrono-c53c9ce4",
    title: "一·二八事变",
    year: 1932,
    track: "china",
    category: "战争",
    summary: "1932年1月28日；日军进攻上海；十九路军奋起抵抗；《淞沪停战协定》",
  },
  {
    id: "chrono-2d7a500b",
    title: "伪满洲国成立",
    year: 1932,
    track: "china",
    category: "政治",
    summary: "1932年3月；日本扶植溥仪建立傀儡政权；东北沦陷；殖民统治开始",
  },
  {
    id: "chrono-1abe4f84",
    title: "罗斯福新政开始",
    year: 1933,
    track: "world",
    category: "社会",
    summary: "罗斯福实行新政；国家干预经济；缓解危机；开创国家垄断资本主义新模式",
  },
  {
    id: "chrono-0bc3181f",
    title: "希特勒上台",
    year: 1933,
    track: "world",
    category: "社会",
    summary: "希特勒上台组阁；建立纳粹独裁统治；欧洲战争策源地形成",
  },
  {
    id: "chrono-2ca46edd",
    title: "红军长征",
    year: 1934,
    endYear: 1936,
    track: "china",
    category: "社会",
    summary: "红军进行战略转移；长征两万五千里；保存革命力量；沿途传播革命思想",
  },
  {
    id: "chrono-7305e59e",
    title: "遵义会议",
    year: 1935,
    track: "china",
    category: "社会",
    summary: "遵义会议召开；确立毛泽东在党中央的领导地位；党的历史上生死攸关的转折点",
  },
  {
    id: "chrono-8d02736b",
    title: "意大利入侵埃塞俄比亚",
    year: 1935,
    track: "world",
    category: "战争",
    summary: "意大利入侵埃塞俄比亚；英法绥靖政策纵容；法西斯侵略气焰加剧",
  },
  {
    id: "chrono-02f5c100",
    title: "一二·九运动",
    year: 1935,
    track: "china",
    category: "社会",
    summary: "1935年12月9日；北平学生抗日救亡运动；促进民族觉醒；推动抗日民族统一战线",
  },
  {
    id: "chrono-7d1411f6",
    title: "西安事变和平解决",
    year: 1936,
    track: "china",
    category: "社会",
    summary: "张学良杨虎城发动西安事变；逼迫蒋介石抗日；和平解决后统一战线初步形成",
  },
  {
    id: "chrono-68ddf621",
    title: "抗日民族统一战线初步形成",
    year: 1936,
    track: "china",
    category: "政治",
    summary: "西安事变和平解决；国共停止内战；抗日民族统一战线初步形成",
  },
  {
    id: "chrono-c57afb91",
    title: "西班牙内战爆发",
    year: 1936,
    track: "world",
    category: "社会",
    summary: "西班牙内战爆发；德意干涉支持佛朗哥；成为二战前哨战",
  },
  {
    id: "chrono-836dcbda",
    title: "七七事变",
    year: 1937,
    track: "china",
    category: "社会",
    summary: "日军制造七七事变；全面侵华开始；中国全民族抗战爆发",
  },
  {
    id: "chrono-63419375",
    title: "全面抗战爆发",
    year: 1937,
    track: "china",
    category: "社会",
    summary: "七七事变后中国全面抗战；国共合作共同抗日；开辟世界反法西斯东方战场",
  },
  {
    id: "chrono-85fd8297",
    title: "南京大屠杀",
    year: 1937,
    track: "china",
    category: "社会",
    summary: "日军侵占南京；大肆屠杀中国军民；三十万以上同胞遇难；惨绝人寰的反人类罪行",
  },
  {
    id: "chrono-17294544",
    title: "国共第二次合作",
    year: 1937,
    track: "china",
    category: "社会",
    summary: "国共实现第二次合作；建立抗日民族统一战线；共同抗击日本侵略",
  },
  {
    id: "chrono-b8c217db",
    title: "苏联肃反运动扩大化",
    year: 1937,
    track: "world",
    category: "社会",
    summary: "苏联发动肃反运动并扩大化；大量干部遭清洗；造成严重后果",
  },
  {
    id: "chrono-4c43f425",
    title: "八一三事变，淞沪会战",
    year: 1937,
    track: "china",
    category: "战争",
    summary: "1937年8月13日；日军进攻上海；淞沪会战爆发；粉碎日军三个月灭亡中国企图",
  },
  {
    id: "chrono-1a9300f3",
    title: "洛川会议召开",
    year: 1937,
    track: "china",
    category: "政治",
    summary: "1937年8月22日；洛川会议制定全面抗战路线；确定敌后战场方针",
  },
  {
    id: "chrono-c4e47468",
    title: "平型关大捷",
    year: 1937,
    track: "china",
    category: "战争",
    summary: "1937年9月；八路军一一五师伏击日军；抗战以来首次大捷；打破日军不可战胜神话",
  },
  {
    id: "chrono-ad5df0bf",
    title: "徐州会战，台儿庄大捷",
    year: 1938,
    track: "china",
    category: "战争",
    summary: "1938年1—5月；李宗仁指挥；台儿庄歼敌万余人；抗战正面战场重大胜利",
  },
  {
    id: "chrono-8cb5fdad",
    title: "毛泽东发表《论持久战》",
    year: 1938,
    track: "china",
    category: "思想",
    summary: "1938年5月；毛泽东系统论述持久战战略；驳斥亡国论和速胜论；指明抗战方向",
  },
  {
    id: "chrono-b96b1774",
    title: "武汉会战",
    year: 1938,
    track: "china",
    category: "战争",
    summary: "1938年6—10月；抗战以来规模最大战役；日军伤亡惨重；抗战进入相持阶段",
  },
  {
    id: "chrono-54a7c6fb",
    title: "德国入侵波兰",
    year: 1939,
    track: "world",
    category: "战争",
    summary: "德国闪击波兰；英法对德宣战；第二次世界大战全面爆发",
  },
  {
    id: "chrono-b7338d02",
    title: "百团大战",
    year: 1940,
    track: "china",
    category: "社会",
    summary: "八路军发动百团大战；主动出击日军；沉重打击日军士气；鼓舞全国抗战信心",
  },
  {
    id: "chrono-3703bbab",
    title: "汪精卫成立伪国民政府",
    year: 1940,
    track: "china",
    category: "政治",
    summary: "1940年3月；汪精卫在南京建立伪政权；汉奸卖国；遭全国唾弃",
  },
  {
    id: "chrono-bfa50a50",
    title: "德国入侵苏联",
    year: 1941,
    track: "world",
    category: "战争",
    summary: "德国撕毁互不侵犯条约；突袭苏联；苏德战争爆发；二战规模扩大",
  },
  {
    id: "chrono-20e15d31",
    title: "日本偷袭珍珠港",
    year: 1941,
    track: "world",
    category: "社会",
    summary: "日本偷袭珍珠港；美国太平洋舰队重创；太平洋战争爆发；二战达到最大规模",
  },
  {
    id: "chrono-08ea9453",
    title: "皖南事变",
    year: 1941,
    track: "china",
    category: "战争",
    summary: "1941年1月；国民党袭击新四军；千古奇冤；国共合作遭受严重破坏",
  },
  {
    id: "chrono-1e15b34a",
    title: "第三次长沙会战",
    year: 1941,
    track: "china",
    category: "战争",
    summary: "1941年12月；长沙会战重创日军；太平洋战争初期盟军唯一胜利",
  },
  {
    id: "chrono-91cff41f",
    title: "《联合国家宣言》发表",
    year: 1942,
    track: "world",
    category: "社会",
    summary: "二十六国签署《联合国家宣言》；世界反法西斯同盟正式形成；协同作战",
  },
  {
    id: "chrono-18a3dff4",
    title: "世界反法西斯同盟形成",
    year: 1942,
    track: "world",
    category: "社会",
    summary: "反法西斯同盟形成；各国协同作战；为最终胜利奠定基础",
  },
  {
    id: "chrono-60ec2964",
    title: "世界反法西斯统一战线形成",
    year: 1942,
    track: "world",
    category: "社会",
    summary: "1942年1月；26国签署《联合国家宣言》；反法西斯同盟正式形成",
  },
  {
    id: "chrono-fd836804",
    title: "斯大林格勒战役胜利（二战转折点）",
    year: 1943,
    track: "world",
    category: "战争",
    summary: "苏军在斯大林格勒取得胜利；扭转苏德战场局势；成为二战重要转折点",
  },
  {
    id: "chrono-1d5c8fb9",
    title: "台湾光复",
    year: 1945,
    track: "china",
    category: "社会",
    summary: "抗战胜利后台湾回归祖国；结束日本五十年殖民统治；洗刷民族耻辱",
  },
  {
    id: "chrono-a08ee3b3",
    title: "重庆谈判",
    year: 1945,
    track: "china",
    category: "社会",
    summary: "国共两党进行重庆谈判；签订双十协定；争取和平建国；但内战危机未消",
  },
  {
    id: "chrono-9b14a0df",
    title: "雅尔塔会议",
    year: 1945,
    track: "world",
    category: "社会",
    summary: "美英苏召开雅尔塔会议；商讨战后秩序；划分势力范围；奠定战后格局",
  },
  {
    id: "chrono-6a9877f4",
    title: "二战结束",
    year: 1945,
    track: "world",
    category: "社会",
    summary: "德国日本相继投降；第二次世界大战结束；世界反法西斯战争胜利",
  },
  {
    id: "chrono-1e80edb9",
    title: "波茨坦会议",
    year: 1945,
    track: "world",
    category: "社会",
    summary: "美英苏召开波茨坦会议；敦促日本投降；商讨战后对德处置",
  },
  {
    id: "chrono-ba34f20f",
    title: "中共七大召开",
    year: 1945,
    track: "china",
    category: "政治",
    summary: "1945年4—6月；中共七大确立毛泽东思想为指导思想；制定建立新中国的路线",
  },
  {
    id: "chrono-74f555a8",
    title: "日本无条件投降",
    year: 1945,
    track: "china",
    category: "战争",
    summary: "1945年8月15日；日本宣布无条件投降；9月2日正式签署投降书；抗战胜利结束",
  },
  {
    id: "chrono-5d9a3064",
    title: "全面内战爆发",
    year: 1946,
    track: "china",
    category: "社会",
    summary: "国民党撕毁停战协定；全面进攻解放区；全面内战爆发",
  },
  {
    id: "chrono-dda3154f",
    title: "杜鲁门主义出台",
    year: 1947,
    track: "world",
    category: "社会",
    summary: "杜鲁门主义出台；美苏对抗开始；冷战正式拉开序幕",
  },
  {
    id: "chrono-1b05faaa",
    title: "马歇尔计划",
    year: 1947,
    track: "world",
    category: "社会",
    summary: "美国实施马歇尔计划；援助西欧经济复兴；遏制共产主义扩张；巩固西方阵营",
  },
  {
    id: "chrono-2789e296",
    title: "《中国土地法大纲》颁布",
    year: 1947,
    track: "china",
    category: "社会",
    summary: "1947年；全国土地会议颁布；废除封建剥削土地制度；实行耕者有其田",
  },
  {
    id: "chrono-bbd390f1",
    title: "辽沈战役",
    year: 1948,
    track: "china",
    category: "战争",
    summary: "1948年9—11月；林彪罗荣桓指挥；解放东北全境；解放军数量首超国军",
  },
  {
    id: "chrono-452d98c4",
    title: "淮海战役、平津战役",
    year: 1948,
    track: "china",
    category: "战争",
    summary: "1948年11月—1949年1月；淮海战役歼敌55万；平津战役和平解放北平",
  },
  {
    id: "chrono-1df20f1a",
    title: "新民主主义革命胜利",
    year: 1949,
    track: "china",
    category: "战争",
    summary: "解放战争胜利；中华人民共和国成立；新民主主义革命取得全国胜利",
  },
  {
    id: "chrono-1a4593d5",
    title: "北大西洋公约组织（北约）成立",
    year: 1949,
    track: "world",
    category: "社会",
    summary: "美国牵头成立北约；建立西方军事同盟；冷战军事对峙格局形成",
  },
  {
    id: "chrono-74013b1e",
    title: "德国分裂",
    year: 1949,
    track: "world",
    category: "社会",
    summary: "德国正式分裂为东西两国；东西方对峙的象征；冷战格局具体化",
  },
  {
    id: "chrono-5ca73e66",
    title: "渡江战役",
    year: 1949,
    track: "china",
    category: "战争",
    summary: "1949年4月21日；百万雄师横渡长江；解放南京；国民党政权覆灭",
  },
  {
    id: "chrono-227c5179",
    title: "中国人民政治协商会议召开",
    year: 1949,
    track: "china",
    category: "政治",
    summary: "1949年9月；第一届政协会议召开；通过《共同纲领》；新中国筹备完成",
  },
  {
    id: "chrono-4d812530",
    title: "中华人民共和国成立",
    year: 1949,
    track: "china",
    category: "政治",
    summary: "1949年10月1日；毛泽东宣告中华人民共和国成立；中国人民站起来了",
  },
  {
    id: "chrono-644a3327",
    title: "《中苏友好同盟互助条约》",
    year: 1950,
    track: "china",
    category: "政治",
    summary: "中苏签订友好同盟互助条约；确立同盟关系；保障新中国安全",
  },
  {
    id: "chrono-a58eb42f",
    title: "土地改革开始",
    year: 1950,
    track: "china",
    category: "思想",
    summary: "新中国开展土地改革；废除封建土地制度；解放农村生产力；巩固政权",
  },
  {
    id: "chrono-dfbe9e16",
    title: "朝鲜战争",
    year: 1950,
    endYear: 1953,
    track: "world",
    category: "战争",
    summary: "朝鲜战争爆发；美国介入；中国抗美援朝；维护国家安全；提高国际地位",
  },
  {
    id: "chrono-e48d9c6f",
    title: "抗美援朝战争",
    year: 1950,
    endYear: 1953,
    track: "china",
    category: "战争",
    summary: "1950—1953年；中国人民志愿军赴朝作战；保家卫国；提高国际地位",
  },
  {
    id: "chrono-7af507be",
    title: "第一个五年计划开始",
    year: 1953,
    track: "china",
    category: "社会",
    summary: "中国实施第一个五年计划；优先发展重工业；开启社会主义工业化进程",
  },
  {
    id: "chrono-bdc03018",
    title: "和平共处五项原则提出",
    year: 1953,
    track: "china",
    category: "社会",
    summary: "中国提出和平共处五项原则；成为国际关系基本准则；推动万隆会议外交",
  },
  {
    id: "chrono-2525aeb7",
    title: "斯大林逝世",
    year: 1953,
    track: "world",
    category: "社会",
    summary: "斯大林逝世；结束其近三十年统治；苏联进入过渡时期",
  },
  {
    id: "chrono-ff555cd4",
    title: "赫鲁晓夫上台",
    year: 1953,
    track: "world",
    category: "社会",
    summary: "赫鲁晓夫上台；开始调整斯大林路线；苏联进入新的政治时期",
  },
  {
    id: "chrono-95f3fd4d",
    title: "第一届全国人大召开",
    year: 1954,
    track: "china",
    category: "社会",
    summary: "第一届全国人大召开；制定《中华人民共和国宪法》；确立人民代表大会制度",
  },
  {
    id: "chrono-649dd0a1",
    title: "《中华人民共和国宪法》颁布",
    year: 1954,
    track: "china",
    category: "政治",
    summary: "第一届全国人大颁布宪法；确立人民代表大会制度；中国首部社会主义类型宪法",
  },
  {
    id: "chrono-5b9cd407",
    title: "日内瓦会议",
    year: 1954,
    track: "world",
    category: "社会",
    summary: "日内瓦会议召开；讨论朝鲜和印度支那问题；中国首次以大国身份参与国际会议",
  },
  {
    id: "chrono-c973fc1f",
    title: "华沙条约组织（华约）成立",
    year: 1955,
    track: "world",
    category: "政治",
    summary: "苏联牵头成立华约；与北约形成军事对峙；两极格局正式形成",
  },
  {
    id: "chrono-9afb0e69",
    title: "两极格局正式形成",
    year: 1955,
    track: "world",
    category: "社会",
    summary: "华约成立后；两大军事集团对峙；两极格局正式形成；冷战全面展开",
  },
  {
    id: "chrono-67a20d12",
    title: "万隆会议",
    year: 1955,
    track: "china",
    category: "交流",
    summary: "1955年；周恩来率团参加万隆会议；提出求同存异方针；亚非团结反帝",
  },
  {
    id: "chrono-5736679a",
    title: "三大改造完成",
    year: 1956,
    track: "china",
    category: "社会",
    summary: "中国完成三大改造；消灭私有制；社会主义经济制度基本建立",
  },
  {
    id: "chrono-4bce8f2a",
    title: "社会主义制度建立",
    year: 1956,
    track: "china",
    category: "政治",
    summary: "三大改造完成后；社会主义制度在中国基本建立；进入社会主义初级阶段",
  },
  {
    id: "chrono-20bcc0f4",
    title: "中共八大召开",
    year: 1956,
    track: "china",
    category: "社会",
    summary: "中共八大召开；正确分析国内主要矛盾；提出发展生产力的任务",
  },
  {
    id: "chrono-8d74c8c7",
    title: "苏共二十大",
    year: 1956,
    track: "world",
    category: "社会",
    summary: "苏共召开二十大；赫鲁晓夫批判斯大林；引发国际共运大动荡",
  },
  {
    id: "chrono-bc71230f",
    title: "赫鲁晓夫秘密报告",
    year: 1956,
    track: "world",
    category: "社会",
    summary: "赫鲁晓夫发表秘密报告；全盘否定斯大林；引发社会主义阵营思想混乱",
  },
  {
    id: "chrono-dba3ed0f",
    title: "埃及收回苏伊士运河主权",
    year: 1956,
    track: "world",
    category: "政治",
    summary: "1956年；纳赛尔宣布收回苏伊士运河；引发苏伊士运河危机；亚非拉反殖民斗争",
  },
  {
    id: "chrono-6f821a77",
    title: "苏联发射第一颗人造地球卫星",
    year: 1957,
    track: "world",
    category: "社会",
    summary: "苏联发射第一颗人造卫星；开创太空时代；标志太空竞赛开始",
  },
  {
    id: "chrono-f7703b8c",
    title: "不结盟运动成立",
    year: 1961,
    track: "world",
    category: "社会",
    summary: "亚非拉国家发起不结盟运动；奉行独立自主外交；推动第三世界崛起",
  },
  {
    id: "chrono-7fc2f570",
    title: "古巴宣布为社会主义国家",
    year: 1961,
    track: "world",
    category: "政治",
    summary: "1961年；卡斯特罗宣布古巴走社会主义道路；西半球第一个社会主义国家",
  },
  {
    id: "chrono-8d785b70",
    title: "古巴导弹危机",
    year: 1962,
    track: "world",
    category: "战争",
    summary: "美苏因古巴导弹部署引发危机；核战争一触即发；最终和平解决；推动军控谈判",
  },
  {
    id: "chrono-3f9815f3",
    title: "阿尔及利亚独立",
    year: 1962,
    track: "world",
    category: "政治",
    summary: "1962年；阿尔及利亚经过八年战争获得独立；法国殖民统治结束",
  },
  {
    id: "chrono-437a779c",
    title: "第一颗原子弹爆炸成功",
    year: 1964,
    track: "china",
    category: "科技",
    summary: "中国第一颗原子弹爆炸成功；打破核垄断；提升国防实力与国际地位",
  },
  {
    id: "chrono-a3f6b34d",
    title: "柏林墙修建",
    year: 1964,
    track: "world",
    category: "社会",
    summary: "东德修建柏林墙；分割东西柏林；冷战对峙的标志性象征",
  },
  {
    id: "chrono-5e06a08c",
    title: "提出四个现代化",
    year: 1964,
    track: "china",
    category: "政治",
    summary: "1964年；三届全国人大一次会议提出四个现代化目标；宏伟建设蓝图",
  },
  {
    id: "chrono-1e6e090d",
    title: "第三次中东战争",
    year: 1966,
    endYear: 1976,
    track: "world",
    category: "战争",
    summary: "第三次中东战争爆发；以色列迅速获胜；改变中东格局；阿以矛盾加深",
  },
  {
    id: "chrono-c2318767",
    title: "欧共体成立",
    year: 1967,
    track: "world",
    category: "社会",
    summary: "欧洲六国成立欧共体；推动欧洲经济一体化；提升欧洲国际地位",
  },
  {
    id: "chrono-0e03b5fd",
    title: "第一颗氢弹爆炸成功",
    year: 1967,
    track: "china",
    category: "科技",
    summary: "1967年；中国成功试爆第一颗氢弹；从原子弹到氢弹仅用两年八个月",
  },
  {
    id: "chrono-6850d40d",
    title: "美苏缓和",
    year: 1970,
    track: "world",
    category: "社会",
    summary: "美苏关系进入缓和期；军控谈判取得进展；但竞争本质未变",
  },
  {
    id: "chrono-75a8b4f1",
    title: "中美关系正常化",
    year: 1970,
    track: "world",
    category: "社会",
    summary: "中美关系逐步正常化；结束长期对抗；改变冷战格局",
  },
  {
    id: "chrono-97fa8595",
    title: "第一颗人造地球卫星发射成功",
    year: 1970,
    track: "china",
    category: "科技",
    summary: "1970年；东方红一号卫星发射成功；中国成为第五个能独立发射卫星的国家",
  },
  {
    id: "chrono-3edebb07",
    title: "中华人民共和国恢复在联合国的合法席位",
    year: 1971,
    track: "china",
    category: "政治",
    summary: "第26届联大通过决议；恢复中华人民共和国在联合国合法席位；中国外交重大突破",
  },
  {
    id: "chrono-992276f9",
    title: "尼克松访华（中美关系正常化）",
    year: 1972,
    track: "world",
    category: "社会",
    summary: "尼克松访华；中美关系正常化；改变世界战略格局",
  },
  {
    id: "chrono-2f6f58b1",
    title: "中日正式建交",
    year: 1972,
    track: "china",
    category: "交流",
    summary: "1972年；田中角荣访华；中日正式建立外交关系；邦交正常化",
  },
  {
    id: "chrono-234fe5b5",
    title: "中共十一届三中全会",
    year: 1978,
    track: "china",
    category: "社会",
    summary: "中共十一届三中全会召开；拨乱反正；确立改革开放方针；实现历史性转折",
  },
  {
    id: "chrono-ecccf37c",
    title: "苏联入侵阿富汗",
    year: 1978,
    track: "world",
    category: "战争",
    summary: "苏联入侵阿富汗；陷入十年战争泥潭；消耗国力；加速苏联衰败",
  },
  {
    id: "chrono-9ebd2622",
    title: "中美建交",
    year: 1979,
    track: "world",
    category: "社会",
    summary: "中美正式建交；结束三十年不正常关系；推动两国交流合作",
  },
  {
    id: "chrono-0771c85d",
    title: "深圳、珠海、汕头、厦门设立经济特区",
    year: 1980,
    track: "china",
    category: "社会",
    summary: "中央决定设立深圳珠海汕头厦门经济特区；开启对外开放窗口；吸引外资技术",
  },
  {
    id: "chrono-704bec30",
    title: "中共十二大提出建设有中国特色的社会主义",
    year: 1982,
    track: "china",
    category: "社会",
    summary: "中共十二大提出建设有中国特色的社会主义；确立新时期指导思想",
  },
  {
    id: "chrono-bc8cbb50",
    title: "新修改的《中华人民共和国宪法》通过",
    year: 1982,
    track: "china",
    category: "政治",
    summary: "1982年12月；五届全国人大五次会议通过新宪法；现行宪法；依法治国基础",
  },
  {
    id: "chrono-5b7e8f08",
    title: "开放14个沿海港口城市",
    year: 1984,
    track: "china",
    category: "社会",
    summary: "1984年；开放大连秦皇岛等14个沿海港口城市；对外开放格局扩大",
  },
  {
    id: "chrono-7dc27e37",
    title: "戈尔巴乔夫改革开始",
    year: 1985,
    track: "world",
    category: "思想",
    summary: "戈尔巴乔夫上台推行改革；先经济后政治；改革失控；加速苏联解体",
  },
  {
    id: "chrono-43a898da",
    title: "中共十三大召开",
    year: 1987,
    track: "china",
    category: "政治",
    summary: "1987年10月；确立社会主义初级阶段理论；提出一个中心两个基本点",
  },
  {
    id: "chrono-0fe639fd",
    title: "东欧剧变开始",
    year: 1989,
    track: "world",
    category: "社会",
    summary: "东欧各国政局剧变；共产党相继失去执政地位；社会主义阵营瓦解",
  },
  {
    id: "chrono-d7df3f53",
    title: "东欧剧变",
    year: 1989,
    track: "world",
    category: "社会",
    summary: "东欧各国共产党相继下台；政权更迭；华约体系瓦解；冷战格局松动",
  },
  {
    id: "chrono-995a15ca",
    title: "柏林墙倒塌",
    year: 1989,
    track: "world",
    category: "社会",
    summary: "柏林墙倒塌；标志冷战格局瓦解；德国统一进程启动",
  },
  {
    id: "chrono-d438f55a",
    title: "中共十三届四中全会",
    year: 1989,
    track: "china",
    category: "政治",
    summary: "1989年6月；江泽民当选总书记；第三代领导集体形成",
  },
  {
    id: "chrono-c07ae8e0",
    title: "苏联解体",
    year: 1991,
    track: "world",
    category: "社会",
    summary: "苏联正式解体；两极格局终结；冷战结束；世界进入多极化过渡期",
  },
  {
    id: "chrono-5344d32c",
    title: "邓小平南方谈话",
    year: 1992,
    track: "china",
    category: "社会",
    summary: "邓小平发表南方谈话；澄清姓资姓社争论；推动改革开放深化",
  },
  {
    id: "chrono-cb5ea023",
    title: "中共十四大确立社会主义市场经济体制目标",
    year: 1992,
    track: "china",
    category: "社会",
    summary: "中共十四大确立社会主义市场经济体制目标；推动经济体制改革深化",
  },
  {
    id: "chrono-0887840c",
    title: "欧洲联盟（欧盟）正式成立",
    year: 1993,
    track: "world",
    category: "社会",
    summary: "欧洲联盟正式成立；欧洲一体化迈出重要步伐；欧元区逐步形成",
  },
  {
    id: "chrono-bfc42fe2",
    title: "汪辜会谈",
    year: 1993,
    track: "china",
    category: "交流",
    summary: "1993年；汪道涵与辜振甫在新加坡会谈；两岸关系迈出重要一步",
  },
  {
    id: "chrono-9290adbe",
    title: "世界贸易组织（WTO）成立",
    year: 1995,
    track: "world",
    category: "交流",
    summary: "世界贸易组织正式成立；推动全球贸易自由化；经济全球化加速",
  },
  {
    id: "chrono-c2fcf8cb",
    title: "香港回归祖国",
    year: 1997,
    track: "china",
    category: "社会",
    summary: "中国恢复对香港行使主权；一国两制首次实践；洗刷百年屈辱",
  },
  {
    id: "chrono-27a949e7",
    title: "中共十五大确立邓小平理论为党的指导思想",
    year: 1997,
    track: "china",
    category: "思想",
    summary: "中共十五大确立邓小平理论为指导思想；推动改革开放事业继续前进",
  },
  {
    id: "chrono-b7299691",
    title: "欧元启动",
    year: 1997,
    track: "world",
    category: "社会",
    summary: "欧元正式启动；欧洲经济货币一体化取得突破；挑战美元霸权",
  },
  {
    id: "chrono-dd0b324d",
    title: "亚洲金融危机",
    year: 1997,
    track: "world",
    category: "社会",
    summary: "1997年；泰国金融危机波及亚洲；中国经济保持稳定；人民币不贬值",
  },
  {
    id: "chrono-59d02a24",
    title: "北约轰炸南联盟",
    year: 1999,
    track: "world",
    category: "战争",
    summary: "北约轰炸南联盟；绕过联合国发动战争；国际关系准则受挑战",
  },
  {
    id: "chrono-019735e7",
    title: "澳门回归祖国",
    year: 1999,
    track: "china",
    category: "社会",
    summary: "中国恢复对澳门行使主权；一国两制再实践；殖民遗产基本清算",
  },
  {
    id: "chrono-61a31fb9",
    title: "美国发动阿富汗战争",
    year: 1999,
    track: "world",
    category: "战争",
    summary: "美国发动阿富汗战争；推翻塔利班政权；反恐战争开端",
  },
  {
    id: "chrono-0d9295cc",
    title: "科索沃战争",
    year: 1999,
    track: "world",
    category: "战争",
    summary: "科索沃战争爆发；北约空袭南联盟；人道主义干预争议；国际秩序受冲击",
  },
  {
    id: "chrono-c43ea255",
    title: "二十国集团成立",
    year: 1999,
    track: "world",
    category: "社会",
    summary: "1999年；G20成立；国际经济合作论坛；全球治理机制完善",
  },
  {
    id: "chrono-189c76c0",
    title: "巴拿马收回运河区全部主权",
    year: 1999,
    track: "world",
    category: "政治",
    summary: "1999年；巴拿马收回运河全部主权；美国长期控制终结；拉美反殖胜利",
  },
  {
    id: "chrono-51339681",
    title: "上海合作组织成立",
    year: 2001,
    track: "china",
    category: "社会",
    summary: "上海合作组织成立；推动中亚安全合作；中国主导的多边机制",
  },
  {
    id: "chrono-cac0053b",
    title: "阿富汗战争",
    year: 2001,
    track: "world",
    category: "战争",
    summary: "美国发动阿富汗战争；推翻塔利班政权；反恐战争全面展开",
  },
  {
    id: "chrono-e07ee404",
    title: "中国正式加入世界贸易组织",
    year: 2001,
    track: "china",
    category: "交流",
    summary: "2001年12月；中国正式加入WTO；融入经济全球化；对外开放新阶段",
  },
  {
    id: "chrono-611e4b0f",
    title: "中共十六大召开",
    year: 2002,
    track: "china",
    category: "政治",
    summary: "2002年11月；三个代表重要思想确立为指导思想；胡锦涛当选总书记",
  },
  {
    id: "chrono-a8aee1b6",
    title: "伊拉克战争",
    year: 2003,
    track: "world",
    category: "战争",
    summary: "美国以大规模杀伤性武器为由发动战争；推翻萨达姆政权；中东格局动荡",
  },
  {
    id: "chrono-9eeead32",
    title: "通过《反分裂国家法》",
    year: 2005,
    track: "china",
    category: "政治",
    summary: "2005年3月；全国人大通过《反分裂国家法》；反对台独分裂的法律武器",
  },
  {
    id: "chrono-be3be2bb",
    title: "取消农业税",
    year: 2006,
    track: "china",
    category: "社会",
    summary: "2006年；中国全面取消农业税；延续2600年的皇粮国税终结；惠及九亿农民",
  },
  {
    id: "chrono-cc4cef8c",
    title: "中共十七大召开",
    year: 2007,
    track: "china",
    category: "政治",
    summary: "2007年10月；科学发展观写入党章；中国特色社会主义理论体系确立",
  },
  {
    id: "chrono-79bfd3d8",
    title: "北京奥运会成功举办",
    year: 2008,
    track: "china",
    category: "社会",
    summary: "北京成功举办奥运会；展示国家形象；提升国际影响力；民族自信增强",
  },
  {
    id: "chrono-6690ceee",
    title: "神舟七号载人航天飞行",
    year: 2008,
    track: "china",
    category: "科技",
    summary: "神舟七号载人航天飞行成功；中国宇航员首次太空行走；航天技术重大突破",
  },
  {
    id: "chrono-0eb1ce88",
    title: "国际金融危机爆发",
    year: 2008,
    track: "world",
    category: "社会",
    summary: "美国次贷危机引发全球金融危机；世界经济衰退；暴露金融体系缺陷",
  },
  {
    id: "chrono-4785da9d",
    title: "叙利亚爆发内战",
    year: 2011,
    track: "world",
    category: "战争",
    summary: "2011年；叙利亚内战爆发；难民危机席卷欧洲；中东格局深刻动荡",
  },
  {
    id: "chrono-49c6d544",
    title: "中共十八大召开",
    year: 2012,
    track: "china",
    category: "社会",
    summary: "中共十八大召开；确立全面建成小康社会目标；新一代领导集体接班",
  },
  {
    id: "chrono-f6e1e29f",
    title: "提出共建一带一路倡议",
    year: 2013,
    track: "china",
    category: "交流",
    summary: "2013年；习近平提出一带一路倡议；推动沿线国家互联互通；构建人类命运共同体",
  },
  {
    id: "chrono-50837361",
    title: "克里米亚危机",
    year: 2014,
    track: "world",
    category: "社会",
    summary: "俄罗斯吞并克里米亚；引发西方制裁；美俄关系恶化；地缘政治紧张",
  },
  {
    id: "chrono-d58197ec",
    title: "两岸领导人会面",
    year: 2015,
    track: "china",
    category: "交流",
    summary: "2015年11月7日；习近平马英九在新加坡会面；66年来两岸领导人首次直接会面",
  },
  {
    id: "chrono-9277f2d1",
    title: "G20杭州峰会",
    year: 2016,
    track: "china",
    category: "交流",
    summary: "2016年；二十国集团领导人杭州峰会；中国主办；推动全球经济治理改革",
  },
  {
    id: "chrono-ece84634",
    title: "英国脱欧公投",
    year: 2016,
    track: "world",
    category: "社会",
    summary: "2016年；英国公投决定脱离欧盟；欧洲一体化遭受重大挫折；全球化的逆流",
  },
  {
    id: "chrono-2b0cd849",
    title: "中共十九大召开",
    year: 2017,
    track: "china",
    category: "社会",
    summary: "中共十九大召开；中国特色社会主义进入新时代；确立新的历史方位",
  },
  {
    id: "chrono-7625c143",
    title: "习近平新时代中国特色社会主义思想确立",
    year: 2017,
    track: "china",
    category: "思想",
    summary: "习近平新时代中国特色社会主义思想写入党章；确立为指导思想",
  },
  {
    id: "chrono-c397cb17",
    title: "新冠肺炎疫情全球大流行",
    year: 2020,
    track: "world",
    category: "社会",
    summary: "新冠肺炎疫情全球大流行；冲击各国经济社会；推动国际公共卫生合作",
  },
  {
    id: "chrono-7f56659c",
    title: "中国共产党成立100周年",
    year: 2021,
    track: "china",
    category: "社会",
    summary: "中国共产党成立一百周年；实现第一个百年奋斗目标；全面建成小康社会",
  },
  {
    id: "chrono-28c00ed7",
    title: "全面建成小康社会",
    year: 2021,
    track: "china",
    category: "社会",
    summary: "中国宣布全面建成小康社会；实现第一个百年奋斗目标；历史性消除绝对贫困",
  },
  {
    id: "chrono-e9bc5aad",
    title: "中共十九届六中全会",
    year: 2021,
    track: "china",
    category: "政治",
    summary: "2021年11月；通过《中共中央关于党的百年奋斗重大成就和历史经验的决议》",
  },
  {
    id: "chrono-9e0b2367",
    title: "俄乌冲突爆发",
    year: 2022,
    track: "world",
    category: "战争",
    summary: "俄罗斯对乌克兰发动军事行动；引发欧洲最大规模冲突；国际格局深刻调整",
  },
  {
    id: "chrono-bb62f7ba",
    title: "中共二十大召开",
    year: 2022,
    track: "china",
    category: "政治",
    summary: "2022年10月；习近平连任总书记；擘画全面建设社会主义现代化国家蓝图",
  },
];

export const eventById = new Map(events.map((event) => [event.id, event]));

export type CausalLink = {
  from: string;
  to: string;
  description: string;
};

export const causalLinks: CausalLink[] = [
  { from: "chrono-0560c84c", to: "chrono-28e6019c", description: "商鞅变法使秦国富国强兵，为统一六国奠定基础" },
  { from: "chrono-a4ca0f48", to: "chrono-6cdd7790", description: "英国资产阶级革命引发政治变革，最终以光荣革命完成" },
  { from: "chrono-6cdd7790", to: "chrono-6fb40409", description: "光荣革命后颁布《权利法案》，限制王权" },
  
  { from: "chrono-ebf6135d", to: "chrono-47c3d93a", description: "甲午战争中国战败，被迫签订《马关条约》" },
  { from: "chrono-47c3d93a", to: "chrono-40944d54", description: "《马关条约》激起知识分子愤怒，引发公车上书" },
  { from: "chrono-40944d54", to: "chrono-d1701dd7", description: "公车上书推动维新思想传播，最终导致戊戌变法" },
  { from: "chrono-39f98e00", to: "chrono-9da999b2", description: "同盟会成立时提出三民主义作为革命纲领" },
  { from: "chrono-39f98e00", to: "chrono-723eab0b", description: "同盟会领导革命运动，最终推翻清朝统治" },
  { from: "chrono-723eab0b", to: "chrono-c5a3498e", description: "武昌起义后清帝退位，结束两千年帝制" },
  { from: "chrono-c5a3498e", to: "chrono-d3eee214", description: "清帝退位后颁布《临时约法》，确立共和制度" },
  { from: "chrono-893de13c", to: "chrono-835af4e9", description: "巴黎和会外交失败引发五四运动" },
  { from: "chrono-3b831007", to: "chrono-2e19e530", description: "十月革命促进马克思主义传播，推动中国共产党成立" },
  { from: "chrono-28c49fec", to: "chrono-835af4e9", description: "新文化运动启发民智，为五四运动做思想准备" },
  { from: "chrono-b2c7a1f0", to: "chrono-1abe4f84", description: "经济大危机促使罗斯福实行新政" },
  { from: "chrono-b2c7a1f0", to: "chrono-0bc3181f", description: "经济大危机为法西斯上台创造条件" },
  { from: "chrono-54a7c6fb", to: "chrono-6a9877f4", description: "德国入侵波兰，第二次世界大战全面爆发" },
  { from: "chrono-bfa50a50", to: "chrono-18a3dff4", description: "苏德战争爆发推动世界反法西斯同盟形成" },
  
  { from: "chrono-836dcbda", to: "chrono-63419375", description: "七七事变标志着全面抗战爆发" },
  { from: "chrono-68ddf621", to: "chrono-17294544", description: "西安事变和平解决推动国共第二次合作" },
  { from: "chrono-62f3a667", to: "chrono-ad5566b6", description: "马丁·路德宗教改革推动麦哲伦环球航行时代到来" },
  { from: "chrono-9795030b", to: "chrono-65a4b945", description: "普朗克量子论为爱因斯坦相对论提供科学背景" },
  
];

export function getCausalPartners(eventId: string): { partner: HistoryEvent; description: string }[] {
  const results: { partner: HistoryEvent; description: string }[] = [];
  for (const link of causalLinks) {
    if (link.from === eventId) {
      const partner = eventById.get(link.to);
      if (partner) results.push({ partner, description: link.description });
    }
    if (link.to === eventId) {
      const partner = eventById.get(link.from);
      if (partner) results.push({ partner, description: link.description });
    }
  }
  return results;
}

export type Dynasty = {
  id: string;
  label: string;
  dates: string;
  start: number;
  end: number;
  phase: string;
  summary: string;
  world: string;
};

export const dynasties: Dynasty[] = [
  { id: "prehistoric", label: "史前时代", dates: "约前300万年—前3500年", start: -3000000, end: -3501, phase: "人类起源", summary: "人类在非洲出现并扩散至全球，从旧石器的采集狩猎到新石器的农业定居，生活方式发生根本转变。", world: "人类在非洲出现，西亚率先开始农业革命。" },
  { id: "origin", label: "文明起源", dates: "约公元前3500—前2071年", start: -3500, end: -2071, phase: "王朝之前", summary: "农业、城市、公共工程与社会分层逐渐出现，早期国家由此孕育。", world: "两河流域城市兴起，古埃及完成早期统一。" },
  { id: "xia-shang-zhou", label: "夏商周", dates: "约前2070—前221年", start: -2070, end: -222, phase: "早期王朝", summary: "王朝、文字与礼乐制度逐渐成熟，春秋战国的变革孕育思想与制度突破。", world: "希腊城邦、波斯帝国与罗马共和国先后兴起。" },
  { id: "qin-han", label: "秦汉", dates: "前221—220年", start: -221, end: 219, phase: "统一帝国", summary: "大一统国家确立，郡县、文书与统一标准塑造此后两千年的基本政治框架。", world: "地中海由罗马共和国走向帝国，欧亚交通网络扩大。" },
  { id: "division", label: "三国两晋南北朝", dates: "220—581年", start: 220, end: 580, phase: "分裂与交融", summary: "政权并立与人口迁徙重组南北社会，各族群在冲突、迁徙与制度改革中深度交融。", world: "罗马帝国分裂，欧亚大陆进入民族迁徙与宗教传播活跃期。" },
  { id: "sui-tang", label: "隋唐", dates: "581—907年", start: 581, end: 906, phase: "再统一与开放", summary: "再统一、运河与制度创新连接南北，长安成为多文明汇聚的国际都市。", world: "伊斯兰文明兴起，巴格达成为跨区域知识与贸易中心。" },
  { id: "song-liao-jin", label: "五代十国·辽宋夏金", dates: "907—1271年", start: 907, end: 1270, phase: "并立与繁荣", summary: "多个政权长期并立，城市商业、海上贸易与印刷技术推动社会活力。", world: "十字军东征与蒙古扩张改变欧亚大陆的权力和交通。" },
  { id: "yuan", label: "元", dates: "1271—1368年", start: 1271, end: 1367, phase: "欧亚一体化", summary: "中国重新统一并嵌入更辽阔的欧亚帝国网络，人员、物资与知识流动加速。", world: "地中海和亚洲商路相连，黑死病沿贸易网络扩散。" },
  { id: "ming", label: "明", dates: "1368—1644年", start: 1368, end: 1643, phase: "帝国重建与海洋相遇", summary: "王朝秩序重建，郑和远航与白银贸易把中国更深地带入早期全球联系。", world: "文艺复兴、地理大发现与宗教改革重塑欧洲。" },
  { id: "qing", label: "清", dates: "1644—1912年", start: 1644, end: 1911, phase: "多民族国家与近代冲击", summary: "统一多民族国家得到巩固，也在工业化与帝国扩张的全球浪潮中遭遇深刻危机。", world: "科学革命、工业革命和民族国家扩张改变全球力量对比。" },
  { id: "republic", label: "民国时期", dates: "1912—1949年", start: 1912, end: 1948, phase: "共和探索与民族救亡", summary: "共和制度艰难落地，中国在内忧外患、思想激荡与全民抗战中寻找现代国家道路。", world: "两次世界大战、俄国革命与战后国际秩序交替出现。" },
  { id: "prc", label: "中华人民共和国", dates: "1949年至今", start: 1949, end: 9999, phase: "国家建设与改革开放", summary: "新中国完成国家重建，改革开放推动经济社会转型，并在全球化中持续寻找发展道路。", world: "冷战、信息革命与全球治理重塑人类共同生活。" },
];

export function findDynastyForYear(year: number): Dynasty {
  const found = dynasties.find((d) => year >= d.start && year <= d.end);
  if (found) return found;
  return year < dynasties[0].start ? dynasties[0] : dynasties[dynasties.length - 1];
}

export function formatYear(year: number): string {
  if (year < 0) {
    const abs = Math.abs(year);
    if (abs >= 10000) {
      const wan = abs / 10000;
      return `公元前${Number.isInteger(wan) ? wan : wan.toFixed(1)}万年`;
    }
    return `公元前${abs}年`;
  }
  return `${year}年`;
}
